### ISSUE TITLE
python tools/export_model.py 报错 NotImplementedError: ProgramTranslator hasn't implemented multiple decorators. Please remove staticmethod in forward

### ISSUE THREAD

**Issue by liuyang77886** [PaddlePaddle/PaddleYOLO#10]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

python tools/export_model.py -c configs/yolov7/yolov7p6_e6e_300e_coco.yml --output_dir=inference_model -o weights=output/yolov7p6_e6_300e_coco/yolov7p6_e6e_300e_coco.pdparams

(paddle) G:\work_py\notebook\paddle\PaddleDetection_YOLOSeries-develop>python tools/export_model.py -c configs/yolov7/yolov7p6_e6e_300e_coco.yml --output_dir=inference_model -o weights=output/yolov7p6_e6_300e_coco/yolov7p6_e6e_300e_coco.pdparams
C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\urllib3\util\selectors.py:14: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import namedtuple, Mapping
C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\urllib3\_collections.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Mapping, MutableMapping
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
Params:  Tensor(shape=[1], dtype=float32, place=Place(cpu), stop_gradient=False,
       [166.40467834])
[08/21 15:35:43] ppdet.utils.checkpoint INFO: Finish loading model weights: output/yolov7p6_e6_300e_coco/yolov7p6_e6e_300e_coco.pdparams
[08/21 15:35:43] ppdet.data.source.category WARNING: anno_file 'dataset/coco\annotations/instances_val2017.json' is None or not set or not exist, please recheck TrainDataset/EvalDataset/TestDataset.anno_path, otherwise the default categories will be used by metric_type.
[08/21 15:35:43] ppdet.data.source.category WARNING: metric_type: COCO, load default categories of COCO.
[08/21 15:35:43] ppdet.engine INFO: Export inference config file to inference_model\yolov7p6_e6e_300e_coco\infer_cfg.yml
Traceback (most recent call last):
  File "tools/export_model.py", line 108, in <module>
    main()
  File "tools/export_model.py", line 104, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 73, in run
    trainer.export(FLAGS.output_dir)
  File "G:\work_py\notebook\paddle\PaddleDetection_YOLOSeries-develop\ppdet\engine\trainer.py", line 875, in export
    save_dir)
  File "G:\work_py\notebook\paddle\PaddleDetection_YOLOSeries-develop\ppdet\engine\trainer.py", line 834, in _get_infer_cfg_and_input_spec
    input_spec, static_model.forward.main_program,
  File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 580, in main_program
    concrete_program = self.concrete_program
  File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 488, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 528, in concrete_program_specify_input_spec
    *desired_input_spec, with_hook=with_hook)
  File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 790, in _build_once
    **cache_key.kwargs)
  File "<decorator-gen-104>", line 2, in from_func_spec
  File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
NotImplementedError: In transformed code:

    File "G:\work_py\notebook\paddle\PaddleDetection_YOLOSeries-develop\ppdet\modeling\architectures\yolov5.py", line 101, in get_pred
        return self._forward()
    File "G:\work_py\notebook\paddle\PaddleDetection_YOLOSeries-develop\ppdet\modeling\architectures\yolov5.py", line 84, in _forward
        body_feats = self.backbone(self.inputs)
    File "G:\work_py\notebook\paddle\PaddleDetection_YOLOSeries-develop\ppdet\modeling\backbones\csp_darknet.py", line 999, in forward
        x = self.stem(x)
    File "G:\work_py\notebook\paddle\PaddleDetection_YOLOSeries-develop\ppdet\modeling\backbones\csp_darknet.py", line 150, in forward
        return self.conv(outputs)
    File "G:\work_py\notebook\paddle\PaddleDetection_YOLOSeries-develop\ppdet\modeling\backbones\csp_darknet.py", line 87, in forward
            if isinstance(self.act, nn.Silu):
                self.act = SiLU()
            y = self.act(x)
            ~~~~~~~~~~~~~~~ <--- HERE
        return y

    File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\convert_call_func.py", line 246, in convert_call
        forward_func = convert_to_static(forward_func)
    File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 140, in convert_to_static
        static_func = _FUNCTION_CACHE.convert_with_cache(function)
    File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 77, in convert_with_cache
        static_func = self._convert(func)
    File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 115, in _convert
        root_wrapper = self._dygraph_to_static.get_static_ast(root)
    File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\ast_transformer.py", line 62, in get_static_ast
        self.transfer_from_node_type(self.static_analysis_root)
    File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\ast_transformer.py", line 74, in transfer_from_node_type
        self.visit(node_wrapper.node)
    File "E:\pfile\anaconda3\envs\paddle\lib\ast.py", line 271, in visit
        return visitor(node)
    File "E:\pfile\anaconda3\envs\paddle\lib\ast.py", line 326, in generic_visit
        value = self.visit(value)
    File "E:\pfile\anaconda3\envs\paddle\lib\ast.py", line 271, in visit
        return visitor(node)
    File "E:\pfile\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\dygraph_to_static\ast_transformer.py", line 111, in visit_FunctionDef
        + d.id + " in " + self.decorate_func_name)

    NotImplementedError: ProgramTranslator hasn't implemented multiple decorators. Please remove staticmethod in forward


### 复现环境 Environment

paddlepaddle-gpu:  2.3.1.post101
python:3.7
cuda10.1

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
感谢反馈，已修复。

**Comment by STNPSG** [comment]
我也出现这个问题了 请问怎么解决
