### ISSUE TITLE
yolov7训练出错，但paddledection下模型可以正常训练

### ISSUE THREAD

**Issue by Nefefilibata** [PaddlePaddle/PaddleYOLO#105]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[03/14 10:29:24] ppdet.data.source.coco INFO: Load [148 samples valid, 0 samples invalid] in file truck_waste_dataset/train.json.
W0314 10:29:24.923347 19138 gpu_context.cc:244] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W0314 10:29:24.928413 19138 gpu_context.cc:272] device: 0, cuDNN Version: 8.2.
[03/14 10:29:32] ppdet.engine INFO: Epoch: [0] [0/5] eta: 0:51:34 lr: 0.000000 loss_box: 0.070696 loss_cls: 0.000000 loss_obj: 2.573034 loss: 84.599358 batch_cost: 2.0629 data_cost: 0.0154 ips: 15.5121 images/s
Found inf or nan, current scale is: 1024.0, decrease to: 1024.0*0.5
[03/14 10:29:41] ppdet.engine INFO: Epoch: [1] [0/5] eta: 0:39:31 lr: 0.001111 loss_box: 0.069338 loss_cls: 0.000000 loss_obj: 2.558958 loss: 84.025085 batch_cost: 1.5864 data_cost: 0.3137 ips: 20.1710 images/s
[03/14 10:29:49] ppdet.engine INFO: Epoch: [2] [0/5] eta: 0:39:14 lr: 0.004444 loss_box: 0.067980 loss_cls: 0.000000 loss_obj: 2.362961 loss: 67.014153 batch_cost: 1.5802 data_cost: 0.3583 ips: 20.2510 images/s
[03/14 10:29:58] ppdet.engine INFO: Epoch: [3] [0/5] eta: 0:38:38 lr: 0.010000 loss_box: 0.068115 loss_cls: 0.000000 loss_obj: 1.317498 loss: 42.949432 batch_cost: 1.5610 data_cost: 0.3690 ips: 20.5003 images/s
[03/14 10:30:06] ppdet.engine INFO: Epoch: [4] [0/5] eta: 0:38:08 lr: 0.009910 loss_box: 0.067980 loss_cls: 0.000000 loss_obj: 0.335433 loss: 12.828411 batch_cost: 1.5460 data_cost: 0.3696 ips: 20.6981 images/s
[03/14 10:30:15] ppdet.engine INFO: Epoch: [5] [0/5] eta: 0:37:55 lr: 0.009880 loss_box: 0.068115 loss_cls: 0.000000 loss_obj: 0.149012 loss: 7.009061 batch_cost: 1.5427 data_cost: 0.3748 ips: 20.7431 images/s
Traceback (most recent call last):
  File "PaddleYOLO-release-2.6/tools/train.py", line 188, in <module>
    main()
  File "PaddleYOLO-release-2.6/tools/train.py", line 184, in main
    run(FLAGS, cfg)
  File "PaddleYOLO-release-2.6/tools/train.py", line 137, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleYOLO-release-2.6/ppdet/engine/trainer.py", line 414, in train
    outputs = model(data)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 921, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 911, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleYOLO-release-2.6/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/home/aistudio/PaddleYOLO-release-2.6/ppdet/modeling/architectures/yolov7.py", line 95, in get_loss
    return self._forward()
  File "/home/aistudio/PaddleYOLO-release-2.6/ppdet/modeling/architectures/yolov7.py", line 77, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 921, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 911, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleYOLO-release-2.6/ppdet/modeling/heads/yolov7_head.py", line 208, in forward
    return self.loss(yolo_outputs, targets, self.anchors)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 921, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/aistudio/.data/webide/pip/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 911, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleYOLO-release-2.6/ppdet/modeling/losses/yolov7_loss.py", line 132, in forward
    inputs, targets_labels, anchors, batch_images)
  File "/home/aistudio/PaddleYOLO-release-2.6/ppdet/modeling/losses/yolov7_loss.py", line 362, in build_targets
    matching_matrix[gt_idx, pos_idx.numpy()] = 1.0
IndexError: index 139966984950297 is out of bounds for axis 1 with size 6

**Comment by Nefefilibata** [comment]
metric: COCO
num_classes: 1
TrainDataset:
  !COCODataSet
    image_dir: images
    anno_path: train.json
    dataset_dir: truck_waste_dataset
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']
EvalDataset:
  !COCODataSet
    image_dir: images
    anno_path: val.json
    dataset_dir: truck_waste_dataset
    allow_empty: true
其余config与源文件基本相同，调整了batch_size和lr
!python PaddleYOLO-release-2.6/tools/train.py -c PaddleYOLO-release-2.6/configs/yolov7/yolov7_x_300e_coco.yml\
 --use_vdl=True --eval --amp

**Comment by nemonameless** [comment]
可以先不加--amp训练。训练集图片数太少了，要加载coco权重做预训练，
```
pretrain_weights: https://paddledet.bj.bcebos.com/models/yolov7_x_300e_coco.pdparams
```

**Comment by Nefefilibata** [comment]
已解决，感谢
