### ISSUE TITLE
YOLOv5模型改动v7的neck部分后导出报错

### ISSUE THREAD

**Issue by NwTbbetter** [PaddlePaddle/PaddleYOLO#12]
想用yolov7进行训练，所以改了v7的neck部分，也就是改动了yolo_fpn.py里的class ELANFPN(nn.Layer)。
这个函数在yolov5里并不调用吧？
为什么把这个类改了，yolov5模型导出时就会报错（报错信息如下），而把这个类还原则导出正常。

ps（导出yolov5只是用来测试，为什么改了neck部分，v7能进行训练但是不能导出呢）

```
命令：
python tools/export_model.py -c configs/yolov5/yolov5_s_300e_coco.yml --output_dir=output_inference -o weights=/home/bxy/PaddleDetection_YOLOSeries/output/yolov5_s_300e_coco/best_model.pdparams
```

```
Traceback (most recent call last):
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
    outputs = static_func(*inputs)
  File "/tmp/tmpxtr9pgcj.py", line 101, in forward
    false_fn_5, (), (inputs, self), (out,))
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
    out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
    return true_fn(*true_args) if pred else false_fn(*false_args)
  File "/tmp/tmpxtr9pgcj.py", line 84, in false_fn_5
    for_loop_body_0, [__for_loop_var_index_0, inputs_list])
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
    loop_vars = _run_py_while(cond, body, loop_vars)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while
    loop_vars = body(*loop_vars)
  File "/tmp/tmpxtr9pgcj.py", line 79, in for_loop_body_0
    dy2static.convert_call(self.get_pred)())
  File "/tmp/tmpba5askf6.py", line 7, in get_pred
    return paddle.jit.dy2static.convert_call(self._forward)()
  File "/tmp/tmp90e4iv_c.py", line 11, in _forward
    neck_feats = paddle.jit.dy2static.convert_call(self.neck)(body_feats,
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_call_func.py", line 246, in convert_call
    forward_func = convert_to_static(forward_func)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 140, in convert_to_static
    static_func = _FUNCTION_CACHE.convert_with_cache(function)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 77, in convert_with_cache
    static_func = self._convert(func)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 104, in _convert
    source_code = func_to_source_code(func)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 550, in func_to_source_code
    source_code_list, _ = inspect.getsourcelines(function)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/inspect.py", line 782, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 1268: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/export_model.py", line 108, in <module>
    main()
  File "tools/export_model.py", line 104, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 73, in run
    trainer.export(FLAGS.output_dir)
  File "/home/yaozhuohan/bxy/PaddleDetection_YOLOSeries/ppdet/engine/trainer.py", line 875, in export
    save_dir)
  File "/home/yaozhuohan/bxy/PaddleDetection_YOLOSeries/ppdet/engine/trainer.py", line 834, in _get_infer_cfg_and_input_spec
    input_spec, static_model.forward.main_program,
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 580, in main_program
    concrete_program = self.concrete_program
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
    *desired_input_spec, with_hook=with_hook)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
    **cache_key.kwargs)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 327, in raise_new_exception
    new_exception = self.create_exception()
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 161, in create_exception
    new_exception = self.error_type(message)
TypeError: function takes exactly 5 arguments (1 given)
```

### 复现环境 Environment

-PaddlePaddle:2.3.1
-Python:3.7.13
-CUDA:10.1

**Comment by nemonameless** [comment]
怎么改的请说明

**Comment by nemonameless** [comment]
请用现在默认分支代码再试试
