### ISSUE TITLE
yolov7_L训练多卡出现训练不到一个epoch就训练迭代不动的问题

### ISSUE THREAD

**Issue by Daniel-deng-yi** [PaddlePaddle/PaddleYOLO#127]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

TrainReader:
       batch_size: 24

### 复现环境 Environment

I0417 01:46:07.710219   289 nccl_context.cc:83] init nccl context nranks: 4 local rank: 0 gpu id: 0 ring id: 0
W0417 01:46:08.102859   289 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.6, Runtime API Version: 10.1
W0417 01:46:08.106501   289 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.

4张卡 Tesla P40 24G

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
有打印成功几行log信息吗？包括loss什么的。单卡bs=24太大了，可能撑满P40显存了，你调小点再试试

**Comment by Daniel-deng-yi** [comment]
[04/15 04:14:32] ppdet.engine INFO: Epoch: [0] [ 150/1049] eta: 12 days, 0:32:20 lr: 0.000023 loss_box: 0.073600 loss_cls: 0.586154 loss_obj: 0.442521 loss: 109.188599 batch_c                              ost: 7.0544 data_cost: 0.0096 ips: 3.4021 images/s
[04/15 04:15:21] ppdet.engine INFO: Epoch: [0] [ 160/1049] eta: 12 days, 8:40:34 lr: 0.000026 loss_box: 0.073384 loss_cls: 0.573154 loss_obj: 0.329659 loss: 94.069427 batch_co                              st: 4.8034 data_cost: 0.0192 ips: 4.9965 images/s
[04/15 04:16:29] ppdet.engine INFO: Epoch: [0] [ 170/1049] eta: 13 days, 1:35:14 lr: 0.000029 loss_box: 0.073414 loss_cls: 0.551102 loss_obj: 0.244618 loss: 82.995499 batch_co                              st: 6.7072 data_cost: 0.0101 ips: 3.5782 images/s
[04/15 04:17:05] ppdet.engine INFO: Epoch: [0] [ 180/1049] eta: 13 days, 1:39:14 lr: 0.000033 loss_box: 0.073491 loss_cls: 0.580114 loss_obj: 0.185147 loss: 80.806656 batch_co                              st: 3.6051 data_cost: 0.4439 ips: 6.6573 images/s
[04/15 04:17:51] ppdet.engine INFO: Epoch: [0] [ 190/1049] eta: 13 days, 5:53:59 lr: 0.000036 loss_box: 0.070920 loss_cls: 0.523414 loss_obj: 0.141574 loss: 71.846291 batch_co                              st: 4.5205 data_cost: 0.9740 ips: 5.3091 images/s
[04/15 04:18:35] ppdet.engine INFO: Epoch: [0] [ 200/1049] eta: 13 days, 8:36:59 lr: 0.000040 loss_box: 0.075190 loss_cls: 0.508361 loss_obj: 0.112763 loss: 67.844269 batch_co                              st: 4.2662 data_cost: 0.4293 ips: 5.6256 images/s
[04/15 04:19:13] ppdet.engine INFO: Epoch: [0] [ 210/1049] eta: 13 days, 9:02:04 lr: 0.000045 loss_box: 0.072647 loss_cls: 0.519172 loss_obj: 0.086777 loss: 65.679108 batch_co                              st: 3.7734 data_cost: 0.0100 ips: 6.3603 images/s


> 有打印成功几行log信息吗？包括loss什么的。单卡bs=24太大了，可能撑满P40显存了，你调小点再试试

**Comment by Daniel-deng-yi** [comment]
没有报错，直接在这里停滞了

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.6/configs/yolov7/_base_/yolov7_elannet.yml#L2
检查下是否是设置false的。true可能会卡，epoch足够长时sync_bn加不加差别不大

**Comment by Daniel-deng-yi** [comment]
> 

想问下去掉sync_bn后对精度影响有多大，改了后现在训练的很快

**Comment by Daniel-deng-yi** [comment]
> https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.6/configs/yolov7/_base_/yolov7_elannet.yml#L2 检查下是否是设置false的。true可能会卡，epoch足够长时sync_bn加不加差别不大

训着出现了了下面的报错，麻烦帮我看下什么问题！

INFO 2023-04-17 07:39:48,839 launch_utils.py:322] terminate process group gid:139875
INFO 2023-04-17 07:39:48,839 launch_utils.py:322] terminate process group gid:139875
INFO 2023-04-17 07:39:48,857 launch_utils.py:322] terminate process group gid:139880
INFO 2023-04-17 07:39:48,857 launch_utils.py:322] terminate process group gid:139880
INFO 2023-04-17 07:39:48,858 launch_utils.py:322] terminate process group gid:139891
INFO 2023-04-17 07:39:48,858 launch_utils.py:322] terminate process group gid:139891
INFO 2023-04-17 07:39:58,894 launch_utils.py:343] terminate all the procs
INFO 2023-04-17 07:39:58,894 launch_utils.py:343] terminate all the procs
ERROR 2023-04-17 07:39:58,895 launch_utils.py:640] ABORT!!! Out of all 4 trainers, the trainer process with rank=[2] was aborted. Please check its log.
ERROR 2023-04-17 07:39:58,895 launch_utils.py:640] ABORT!!! Out of all 4 trainers, the trainer process with rank=[2] was aborted. Please check its log.
INFO 2023-04-17 07:40:02,898 launch_utils.py:343] terminate all the procs
INFO 2023-04-17 07:40:02,898 launch_utils.py:343] terminate all the procs
INFO 2023-04-17 07:40:02,898 launch.py:402] Local processes completed.
INFO 2023-04-17 07:40:02,898 launch.py:402] Local processes completed

**Comment by nemonameless** [comment]
报错信息提供的太少了，也可以截图。`the trainer process with rank=[2] was aborted. Please check its log.`，就是提示你看下 log_dir 里 workerlog.2 这种名字的日志，有详细的报错信息

**Comment by Daniel-deng-yi** [comment]
> 报错信息提供的太少了，也可以截图。`the trainer process with rank=[2] was aborted. Please check its log.`，就是提示你看下 log_dir 里 workerlog.2 这种名字的日志，有详细的报错信息

哦哦，看到了报错下面的信息

I0417 08:33:36.386785 257658 gen_comm_id_helper.cc:205] Server listening on: 127.0.0.1:38595 successful.
I0417 08:33:39.256733 257658 nccl_context.cc:83] init nccl context nranks: 4 local rank: 2 gpu id: 4 ring id: 0
W0417 08:33:39.917228 257658 gpu_resources.cc:61] Please NOTE: device: 4, GPU Compute Capability: 6.1, Driver API Version: 11.6, Runtime API Version: 10.1
W0417 08:33:39.920608 257658 gpu_resources.cc:91] device: 4, cuDNN Version: 7.6.
loading annotations into memory...
Done (t=1.04s)
creating index...
index created!
W0417 08:34:08.553814 257658 reducer.cc:694] All parameters are involved in the backward pass. It is recommended to set find_unused_parameters to False to improve performance. However, if unused parameters appear in subsequent iterative training, then an error will occur. Please make it clear that in the subsequent training, there will be no parameters that are not used in the backward pass, and then set find_unused_parameters
Traceback (most recent call last):
  File "train.py", line 188, in <module>
    main()
  File "train.py", line 184, in main
    run(FLAGS, cfg)
  File "train.py", line 137, in run
    trainer.train(FLAGS.eval)
  File "/work/01.PaddleYOLO-release-2.5-init/ppdet/engine/trainer.py", line 414, in train
    outputs = model(data)
  File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/parallel.py", line 752, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/work/01.PaddleYOLO-release-2.5-init/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/work/01.PaddleYOLO-release-2.5-init/ppdet/modeling/architectures/yolov7.py", line 95, in get_loss
    return self._forward()
  File "/work/01.PaddleYOLO-release-2.5-init/ppdet/modeling/architectures/yolov7.py", line 77, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/work/01.PaddleYOLO-release-2.5-init/ppdet/modeling/heads/yolov7_head.py", line 208, in forward
    return self.loss(yolo_outputs, targets, self.anchors)
  File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/work/01.PaddleYOLO-release-2.5-init/ppdet/modeling/losses/yolov7_loss.py", line 131, in forward
    bs, as_, gjs, gis, targets, anchors = self.build_targets(
  File "/work/01.PaddleYOLO-release-2.5-init/ppdet/modeling/losses/yolov7_loss.py", line 362, in build_targets
    matching_matrix[gt_idx, pos_idx.numpy()] = 1.0
IndexError: index 1142258600 is out of bounds for axis 1 with size 9

**Comment by JunLei01** [comment]
![image](https://user-images.githubusercontent.com/72364050/232651537-e3c3cc03-8401-4453-98c1-6689460b04ef.png)
训练YOLOv7时出现这个是什么情况？

**Comment by Daniel-deng-yi** [comment]
> > 报错信息提供的太少了，也可以截图。`the trainer process with rank=[2] was aborted. Please check its log.`，就是提示你看下 log_dir 里 workerlog.2 这种名字的日志，有详细的报错信息
> 
> 哦哦，看到了报错下面的信息
> 
> I0417 08:33:36.386785 257658 gen_comm_id_helper.cc:205] Server listening on: 127.0.0.1:38595 successful. I0417 08:33:39.256733 257658 nccl_context.cc:83] init nccl context nranks: 4 local rank: 2 gpu id: 4 ring id: 0 W0417 08:33:39.917228 257658 gpu_resources.cc:61] Please NOTE: device: 4, GPU Compute Capability: 6.1, Driver API Version: 11.6, Runtime API Version: 10.1 W0417 08:33:39.920608 257658 gpu_resources.cc:91] device: 4, cuDNN Version: 7.6. loading annotations into memory... Done (t=1.04s) creating index... index created! W0417 08:34:08.553814 257658 reducer.cc:694] All parameters are involved in the backward pass. It is recommended to set find_unused_parameters to False to improve performance. However, if unused parameters appear in subsequent iterative training, then an error will occur. Please make it clear that in the subsequent training, there will be no parameters that are not used in the backward pass, and then set find_unused_parameters Traceback (most recent call last): File "train.py", line 188, in main() File "train.py", line 184, in main run(FLAGS, cfg) File "train.py", line 137, in run trainer.train(FLAGS.eval) File "/work/01.PaddleYOLO-release-2.5-init/ppdet/engine/trainer.py", line 414, in train outputs = model(data) File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in **call** return self._dygraph_call_func(*inputs, **kwargs) File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func outputs = self.forward(*inputs, **kwargs) File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/parallel.py", line 752, in forward outputs = self._layers(*inputs, **kwargs) File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in **call** return self._dygraph_call_func(*inputs, **kwargs) File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func outputs = self.forward(*inputs, **kwargs) File "/work/01.PaddleYOLO-release-2.5-init/ppdet/modeling/architectures/meta_arch.py", line 59, in forward out = self.get_loss() File "/work/01.PaddleYOLO-release-2.5-init/ppdet/modeling/architectures/yolov7.py", line 95, in get_loss return self._forward() File "/work/01.PaddleYOLO-release-2.5-init/ppdet/modeling/architectures/yolov7.py", line 77, in _forward yolo_losses = self.yolo_head(neck_feats, self.inputs) File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in **call** return self._dygraph_call_func(*inputs, **kwargs) File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func outputs = self.forward(*inputs, **kwargs) File "/work/01.PaddleYOLO-release-2.5-init/ppdet/modeling/heads/yolov7_head.py", line 208, in forward return self.loss(yolo_outputs, targets, self.anchors) File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in **call** return self._dygraph_call_func(*inputs, **kwargs) File "/my_app/anaconda3/envs/paddle_env_py3.8/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func outputs = self.forward(*inputs, **kwargs) File "/work/01.PaddleYOLO-release-2.5-init/ppdet/modeling/losses/yolov7_loss.py", line 131, in forward bs, as_, gjs, gis, targets, anchors = self.build_targets( File "/work/01.PaddleYOLO-release-2.5-init/ppdet/modeling/losses/yolov7_loss.py", line 362, in build_targets matching_matrix[gt_idx, pos_idx.numpy()] = 1.0 IndexError: index 1142258600 is out of bounds for axis 1 with size 9

索引报错是因为分类loss报错，log0为NAN了
修改为：
yolov7_loss,py第354行需要修改成

pairwise_cls_loss = F.binary_cross_entropy_with_logits(
                paddle.log(y / (1 - y) + 1e-5), gt_cls_per_image,
                reduction="none").sum(-1)
