### ISSUE TITLE
YOLOv5 旋转框 训练报错

### ISSUE THREAD

**Issue by gyc137** [PaddlePaddle/PaddleYOLO#131]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

我从DOTA数据集中挑选个别图片作为新数据集，此前用PP-YOLOE-R能够正常训练，而现在用YOLOv5进行训练报错了。
训练命令为python -m paddle.distributed.launch tools/train.py -c configs/yolov5/yolov5_l_300e_coco.yml --eval --use_vdl True --vdl_log_dir output/yolov5_l_100e_dota/scalar

以下为报错内容:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 217, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "/home/gyc/anaconda3/envs/yoloer/lib/python3.8/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "/home/gyc/PaddleYOLO/ppdet/data/reader.py", line 91, in __call__
    batch_data = default_collate_fn(data)
  File "/home/gyc/PaddleYOLO/ppdet/data/utils.py", line 60, in default_collate_fn
    return {
  File "/home/gyc/PaddleYOLO/ppdet/data/utils.py", line 61, in <dictcomp>
    key: default_collate_fn([d[key] for d in batch])
  File "/home/gyc/PaddleYOLO/ppdet/data/utils.py", line 67, in default_collate_fn
    raise RuntimeError(
RuntimeError: fileds number not same among samples in a batch

### 复现环境 Environment

PaddlePaddle版本为2.3.2，其余环境都为推荐配置。

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
请问训练用的是水平框还是旋转框？这个仓库的yolov5不支持旋转框。以及再发点配置文件信息方便排查

**Comment by gyc137** [comment]
是旋转框。那要继续用yolov5进行训练的话，是要把标签文件转为水平框吗?有没有格式转换的参考文件呢?

**Comment by nemonameless** [comment]
旋转框不了解了。看你最终需求是检出旋转框还是水平框。
旋转框 PP-YOLOE-R 应该精度已经足够高，可能没有必要再试别的检测器。
也可向 https://github.com/PaddlePaddle/PaddleDetection/issues 提问
