### ISSUE TITLE
YOLOV7更换inception结构后导出onnx报错

### ISSUE THREAD

**Issue by RAKDSYMCA** [PaddlePaddle/PaddleYOLO#16]
### bug描述 Describe the Bug

修改了csp-darknet.py，将v7最后一层C5的bottlenecks换成了inception结构，训练正常，但导出onnx时报错
导出命令：
```
python tools/export_model.py -c configs/yolov7/yolov7_tiny_300e_coco.yml --output_dir=output_inference -o weights=/home/yaozhuohan/PaddleDetection_YOLOSeries/output/yolov7_tiny_300e_coco/best_model.pdparams
```
报错信息：
```
[09/01 12:17:23] ppdet.engine INFO: Export inference config file to output_inference/yolov7_tiny_300e_coco/infer_cfg.yml
Traceback (most recent call last):
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
    outputs = static_func(*inputs)
  File "/tmp/tmp1ngpwsbj.py", line 101, in forward
    false_fn_5, (), (inputs, self), (out,))
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
    out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
    return true_fn(*true_args) if pred else false_fn(*false_args)
  File "/tmp/tmp1ngpwsbj.py", line 84, in false_fn_5
    for_loop_body_0, [__for_loop_var_index_0, inputs_list])
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
    loop_vars = _run_py_while(cond, body, loop_vars)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while
    loop_vars = body(*loop_vars)
  File "/tmp/tmp1ngpwsbj.py", line 79, in for_loop_body_0
    dy2static.convert_call(self.get_pred)())
  File "/tmp/tmpw0tsf946.py", line 7, in get_pred
    return paddle.jit.dy2static.convert_call(self._forward)()
  File "/tmp/tmpls7f98pk.py", line 10, in _forward
    body_feats = paddle.jit.dy2static.convert_call(self.backbone)(self.inputs)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_call_func.py", line 246, in convert_call
    forward_func = convert_to_static(forward_func)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 140, in convert_to_static
    static_func = _FUNCTION_CACHE.convert_with_cache(function)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 77, in convert_with_cache
    static_func = self._convert(func)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 104, in _convert
    source_code = func_to_source_code(func)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 550, in func_to_source_code
    source_code_list, _ = inspect.getsourcelines(function)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/inspect.py", line 782, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/linecache.py", line 47, in getlines
    return updatecache(filename, module_globals)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/linecache.py", line 137, in updatecache
    lines = fp.readlines()
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 5455: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/export_model.py", line 108, in <module>
    main()
  File "tools/export_model.py", line 104, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 73, in run
    trainer.export(FLAGS.output_dir)
  File "/home/yaozhuohan/PaddleDetection_YOLOSeries/ppdet/engine/trainer.py", line 875, in export
    save_dir)
  File "/home/yaozhuohan/PaddleDetection_YOLOSeries/ppdet/engine/trainer.py", line 834, in _get_infer_cfg_and_input_spec
    input_spec, static_model.forward.main_program,
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 580, in main_program
    concrete_program = self.concrete_program
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
    *desired_input_spec, with_hook=with_hook)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
    **cache_key.kwargs)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 327, in raise_new_exception
    new_exception = self.create_exception()
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 161, in create_exception
    new_exception = self.error_type(message)
TypeError: function takes exactly 5 arguments (1 given)
```

### 复现环境 Environment

-Paddle：2.3.1
-Python：3.7.13

**Comment by nemonameless** [comment]
把改动代码发下，或给个你的分支代码

**Comment by nemonameless** [comment]
请用现在默认分支代码再试试
