### ISSUE TITLE
模型推理和导出时报错

### ISSUE THREAD

**Issue by jia0511** [PaddlePaddle/PaddleYOLO#170]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

训练正常，训练后单张推理图片如下：
python tools/infer.py -c configs/custom/yolov5_s_100e_coco_zhatuche.yml -o weights=output/yolov5_s_100e_coco_zhatuche/model_final.pdparams --infer_img=test0626/5.jpg --save_results True
导出模型推理如下：
python tools/export_model.py -c configs/custom/yolov5_s_100e_coco_zhatuche.yml --output_dir=inference_model -o weights=output/yolov5_s_100e_coco_zhatuche/model_final.pdparams

报错信息如下：
Traceback (most recent call last):
  File "tools/export_model.py", line 107, in <module>
    main()
  File "tools/export_model.py", line 103, in main
    run(FLAGS, cfg)
  File "tools/export_model.py", line 64, in run
    trainer = Trainer(cfg, mode='test')
  File "/home/ubuntu/data1/PaddleYOLO/ppdet/engine/trainer.py", line 83, in __init__
    self.dataset = self.cfg['{}Dataset'.format(capital_mode)] = create(
  File "/home/ubuntu/data1/PaddleYOLO/ppdet/core/workspace.py", line 292, in create
    return cls(**cls_kwargs)
  File "/home/ubuntu/data1/PaddleYOLO/ppdet/data/source/dataset.py", line 278, in __init__
    type = dataset_args.pop("name")
KeyError: 'name'

**Comment by nemonameless** [comment]
推理和导出是看 TestDataset 和 TestReader 的设置，这两个config里的地方检查下看看。

**Comment by jia0511** [comment]
@nemonameless 这是在哪个配置文件中

**Comment by jia0511** [comment]
如果我们的配置文件想设置类别名字在哪个配置文件里，还是会读json标签自动识别

**Comment by jia0511** [comment]
这个问题已经解决，在数据集配置文件中加入TestDataset ，参考https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.6/docs/MODEL_ZOO_cn.md
