### ISSUE TITLE
hello  YOLOv6 training not supported yet.

### ISSUE THREAD

**Issue by WainBK** [PaddlePaddle/PaddleYOLO#179]
### 问题描述 Please describe your issue

Traceback (most recent call last):
  File "/media/server/li/Code/lg/PaddleYOLO-release-2.6/PaddleYOLO-release-2.6/tools/train.py", line 198, in <module>
    main()
  File "/media/server/li/Code/lg/PaddleYOLO-release-2.6/PaddleYOLO-release-2.6/tools/train.py", line 194, in main
    run(FLAGS, cfg)
  File "/media/server/li/Code/lg/PaddleYOLO-release-2.6/PaddleYOLO-release-2.6/tools/train.py", line 138, in run
    trainer = Trainer(cfg, mode='train')
  File "/media/server/li/Code/lg/PaddleYOLO-release-2.6/PaddleYOLO-release-2.6/ppdet/engine/trainer.py", line 76, in __init__
    self.cfg.architecture))
NotImplementedError: YOLOv6 training not supported yet.

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleYOLO/issues/173
已经回复过啦。切换到 yolov6_v20 分支去使用。

**Comment by WainBK** [comment]
谢谢大佬
