### ISSUE TITLE
yolov5u infer出错

### ISSUE THREAD

**Issue by 1340896123** [PaddlePaddle/PaddleYOLO#187]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

python tools/infer.py -c configs/yolov5u/yolov5u_n_300e_coco.yml  -o weights=output/yolov5u_n_300e_coco/69.pdparams  --infer_img=./demo/2.jpg                 
W0908 20:41:52.889870 31864 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.2, Runtime API Version: 11.8
W0908 20:41:52.894870 31864 gpu_resources.cc:149] device: 0, cuDNN Version: 8.6.
[09/08 20:41:54] ppdet.utils.checkpoint INFO: Finish loading model weights: output/yolov5u_n_300e_coco/69.pdparams
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
[09/08 20:41:55] ppdet.engine INFO: Test loader length is 1, test batch_size is 1.
[09/08 20:41:55] ppdet.engine INFO: Starting predicting ......

  0%|                                                                                                                                                          | 0/1 [00:02<?, ?it/s] 
Traceback (most recent call last):
  File "E:\play\DNF\yolov8\PaddleYOLO-develop\tools\infer.py", line 236, in <module>
    main()
  File "E:\play\DNF\yolov8\PaddleYOLO-develop\tools\infer.py", line 232, in main
    run(FLAGS, cfg)
  File "E:\play\DNF\yolov8\PaddleYOLO-develop\tools\infer.py", line 182, in run
    trainer.predict(
  File "E:\play\DNF\yolov8\PaddleYOLO-develop\ppdet\engine\trainer.py", line 890, in predict
    outs = self.model(data)
  File "e:\anaconda3\envs\ppdet\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "E:\play\DNF\yolov8\PaddleYOLO-develop\ppdet\modeling\architectures\meta_arch.py", line 76, in forward
    outs.append(self.get_pred())
  File "E:\play\DNF\yolov8\PaddleYOLO-develop\ppdet\modeling\architectures\yolov5.py", line 96, in get_pred
    return self._forward()
  File "E:\play\DNF\yolov8\PaddleYOLO-develop\ppdet\modeling\architectures\yolov5.py", line 81, in _forward
    post_outs = self.yolo_head.post_process(yolo_head_outs, self.inputs)
TypeError: YOLOv8Head.post_process() missing 1 required positional argument: 'scale_factor'

### 复现环境 Environment

windows
python=3.10

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
已修复，可拉取最新代码使用。
