### ISSUE TITLE
ResourceExhaustedError

### ISSUE THREAD

**Issue by ZhangLe-fighting** [PaddlePaddle/PaddleYOLO#19]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

INFO 2022-09-05 16:54:20,902 launch_utils.py:566] details about PADDLE_TRAINER_ENDPOINTS can be found in ./yolo7_dygraph//endpoints.log, and detail running logs maybe found in ./yolo7_dygraph//workerlog.0
INFO 2022-09-05 16:54:20,902 launch_utils.py:566] details about PADDLE_TRAINER_ENDPOINTS can be found in ./yolo7_dygraph//endpoints.log, and detail running logs maybe found in ./yolo7_dygraph//workerlog.0
launch proc_id:20498 idx:0
launch proc_id:20503 idx:1
launch proc_id:20508 idx:2
launch proc_id:20513 idx:3
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:42005', '127.0.0.1:55637', '127.0.0.1:54941']
I0905 16:54:27.121857 20498 nccl_context.cc:83] init nccl context nranks: 4 local rank: 0 gpu id: 4 ring id: 0
W0905 16:54:28.339090 20498 gpu_resources.cc:61] Please NOTE: device: 4, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 11.2
W0905 16:54:28.343943 20498 gpu_resources.cc:91] device: 4, cuDNN Version: 8.1.
Params:  Tensor(shape=[1], dtype=float32, place=Place(gpu:4), stop_gradient=False,
       [164.94364929])
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/engine/trainer.py", line 520, in train
    outputs = model(data)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/parallel.py", line 752, in forward
    outputs = self._layers(*inputs, **kwargs)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/yolov5.py", line 98, in get_loss
    return self._forward()
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/yolov5.py", line 85, in _forward
    neck_feats = self.neck(body_feats, self.for_mot)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/modeling/necks/yolo_fpn.py", line 1448, in forward
    fpn_out2 = self.elan_fpn2(f_out2)  # 512 -> 128*4 + 256*2 -> 1024 -> 256
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/modeling/backbones/csp_darknet.py", line 519, in forward
    return self.elan_layer1(x) + self.elan_layer2(x)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/modeling/backbones/csp_darknet.py", line 493, in forward
    y = self.conv3(x_all)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/hik/zhangle16/PaddleDetection_YOLOSeries/ppdet/modeling/backbones/csp_darknet.py", line 83, in forward
    x = self.bn(self.conv(x))
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/nn/layer/conv.py", line 678, in forward
    use_cudnn=self._use_cudnn)
  File "/home/hik/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/nn/functional/conv.py", line 144, in _conv_nd
    pre_bias = getattr(_C_ops, op_type)(x, weight, *attrs)
SystemError: (Fatal) Operator conv2d raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 4. Cannot allocate 31.250000MB memory on GPU 4, 22.364380GB memory has been allocated and available memory is only 17.937500MB.

Please check whether there is any other process using GPU 4.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 
If the above ways do not solve the out of memory problem, you can try to use CUDA managed memory. The command is `export FLAGS_use_cuda_managed_memory=false`.
 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:87)
. (at /paddle/paddle/fluid/imperative/tracer.cc:307)

The four cards used are not occupied. By looking at the GPU situation, we can find that the video memory occupation will always show an upward trend and then overflow and report an error. My batchsize is set to 4. Do developers encounter this situation?

**Comment by ZhangLe-fighting** [comment]
![Snipaste_2022-09-05_18-09-41](https://user-images.githubusercontent.com/55420158/188425005-3ba84ab4-5fc0-44de-896b-ecff033ef656.png)

**Comment by ZhangLe-fighting** [comment]
我看到gitee上也有人提出这个问题，但是没检索到解决方法，我的情况和他的类似！

**Comment by nemonameless** [comment]
提问请遵循issue模板，说明下改动了什么，版本和环境是什么，以便排查问题。

**Comment by ZhangLe-fighting** [comment]
改动：只改了配置文件
coco_detection.yml 文件中 num_classes: 4
yolov7p6_elannet.yml 文件中 YOLOv7Head: anchors: [[29, 35], [41, 62], [79, 37], [96, 101], [185, 58], [155, 174], [298, 125], [267, 290], [621, 176], [414, 402], [880, 414], [945, 949]] （tools/anchor_cluster.py 生成）
yolov7p6_reader.yml 文件中 worker_num: 1 ； TrainReader:下batch_size: 4 ； EvalReader:下 batch_size: 4
版本：
paddlepaddle-gpu 2.3.2
paddledet              2.4.0
paddle-bfloat        0.1.7
python                  3.6.2
cudatoolkit           11.2.2 
cudnn                   8.1.0.77           
服务器环境：
Tesla P40 服务器 Linux gpu 4.15.0-142-generic系统
Anaconda下使用conda创建的python3.6的虚拟环境，然后安装了paddle2.3.2 和paddledetection_yoloseries

训练命令：export CUDA_VISIBLE_DEVICES=7
python --log_dir=./yolo7_dygraph/ tools/train.py -c configs/yolov7/yolov7p6_e6e_300e_coco.yml --eval -o use_gpu=true

**Comment by ZhangLe-fighting** [comment]
> ![Snipaste_2022-09-05_18-09-41](https://user-images.githubusercontent.com/55420158/188425005-3ba84ab4-5fc0-44de-896b-ecff033ef656.png)

我的问题和这个有所不同的是，我的刚执行指令就会慢慢的占满显存

**Comment by ZhangLe-fighting** [comment]
上面训练命令采用多卡会造成另一个错误，也已经在问题区进行了提问，期待答复

**Comment by nemonameless** [comment]
一开始训就显存一直上升直到崩溃，就说明bs过大了，调小点就行。
训练命令加上`--amp`混合精度训练，加上可以同bs下减小显存占用。
yolov7p6_e6e是最大的模型，不是一般显卡可以训起来的，训自己的数据集注意要加载coco权重做预训练不要从头训，首页readme写明了。
