### ISSUE TITLE
PaddleYolo训练时报错

### ISSUE THREAD

**Issue by jiangming7301** [PaddlePaddle/PaddleYOLO#203]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

!python -m paddle.distributed.launch PaddleYOLO/tools/train.py -c configs_yolo7/yolov7_tiny_300e_coco.yml --use_vdl=True -o worker_num=4 --eval
报错信息：
LAUNCH INFO 2023-11-29 09:41:12,008 -----------  Configuration  ----------------------
LAUNCH INFO 2023-11-29 09:41:12,009 devices: None
LAUNCH INFO 2023-11-29 09:41:12,009 elastic_level: -1
LAUNCH INFO 2023-11-29 09:41:12,009 elastic_timeout: 30
LAUNCH INFO 2023-11-29 09:41:12,009 gloo_port: 6767
LAUNCH INFO 2023-11-29 09:41:12,009 host: None
LAUNCH INFO 2023-11-29 09:41:12,009 ips: None
LAUNCH INFO 2023-11-29 09:41:12,009 job_id: default
LAUNCH INFO 2023-11-29 09:41:12,009 legacy: False
LAUNCH INFO 2023-11-29 09:41:12,009 log_dir: log
LAUNCH INFO 2023-11-29 09:41:12,009 log_level: INFO
LAUNCH INFO 2023-11-29 09:41:12,009 master: None
LAUNCH INFO 2023-11-29 09:41:12,009 max_restart: 3
LAUNCH INFO 2023-11-29 09:41:12,009 nnodes: 1
LAUNCH INFO 2023-11-29 09:41:12,009 nproc_per_node: None
LAUNCH INFO 2023-11-29 09:41:12,009 rank: -1
LAUNCH INFO 2023-11-29 09:41:12,009 run_mode: collective
LAUNCH INFO 2023-11-29 09:41:12,009 server_num: None
LAUNCH INFO 2023-11-29 09:41:12,009 servers: 
LAUNCH INFO 2023-11-29 09:41:12,009 start_port: 6070
LAUNCH INFO 2023-11-29 09:41:12,009 trainer_num: None
LAUNCH INFO 2023-11-29 09:41:12,009 trainers: 
LAUNCH INFO 2023-11-29 09:41:12,009 training_script: PaddleYOLO/tools/train.py
LAUNCH INFO 2023-11-29 09:41:12,009 training_script_args: ['-c', 'configs_yolo7/yolov7_tiny_300e_coco.yml', '--use_vdl=True', '-o', 'worker_num=4', '--eval']
LAUNCH INFO 2023-11-29 09:41:12,009 with_gloo: 1
LAUNCH INFO 2023-11-29 09:41:12,009 --------------------------------------------------
LAUNCH INFO 2023-11-29 09:41:12,010 Job: default, mode collective, replicas 1[1:1], elastic False
LAUNCH INFO 2023-11-29 09:41:12,023 Run Pod: avdwtn, replicas 1, status ready
LAUNCH INFO 2023-11-29 09:41:12,046 Watching Pod: avdwtn, replicas 1, status running
loading annotations into memory...
Done (t=0.18s)
creating index...
index created!
[11/29 09:41:15] ppdet.data.source.coco INFO: Load [13887 samples valid, 0 samples invalid] in file work/tile/annotations/train_annos_own.json.
W1129 09:41:15.068631  2684 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 12.0, Runtime API Version: 11.2
W1129 09:41:15.074558  2684 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File "PaddleYOLO/tools/train.py", line 198, in <module>
    main()
  File "PaddleYOLO/tools/train.py", line 194, in main
    run(FLAGS, cfg)
  File "PaddleYOLO/tools/train.py", line 147, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleYOLO/ppdet/engine/trainer.py", line 434, in train
    outputs = model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/architectures/meta_arch.py", line 60, in forward
    out = self.get_loss()
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/architectures/yolov7.py", line 95, in get_loss
    return self._forward()
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/architectures/yolov7.py", line 77, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/heads/yolov7_head.py", line 220, in forward
    return self.loss(yolo_outputs, targets, self.anchors)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/losses/yolov7_loss.py", line 175, in forward
    n = b.shape[0]  # number of targets
AttributeError: 'list' object has no attribute 'shape'
LAUNCH INFO 2023-11-29 09:42:05,099 Pod failed
LAUNCH ERROR 2023-11-29 09:42:05,100 Container failed !!!
Container rank 0 status failed cmd ['/opt/conda/envs/python35-paddle120-env/bin/python', '-u', 'PaddleYOLO/tools/train.py', '-c', 'configs_yolo7/yolov7_tiny_300e_coco.yml', '--use_vdl=True', '-o', 'worker_num=4', '--eval'] code 1 log log/workerlog.0 
env {'JUPYTER_6275918_7167826_PORT': 'tcp://10.41.170.61:8888', 'JUPYTER_5985547_7167831_PORT_8888_TCP_ADDR': '10.41.233.181', 'JUPYTER_7642463_7158427_PORT_8888_TCP': 'tcp://10.41.145.190:8888', 'JUPYTER_4942703_7167832_PORT_8888_TCP_PROTO': 'tcp', 'TRAINER_GPU_CARD_COUNT': '1', 'STUDIO_STATIC_URL': 'https://ai-studio-static-online.cdn.bcebos.com/studio-notebook/dist/webide', 'CUDNN_VERSION': '7.3.1.20', 'STUDIO_SERVING_TOKEN': 'token D6E6D737D59B439E9EAC8FBF2A3B7A2FA88395EB81FB46A289AE5D50DB7975E6', 'JUPYTER_6033188_7167881_PORT_8888_TCP': 'tcp://10.41.239.8:8888', 'JUPYTER_989686_7097901_PORT_8888_TCP_ADDR': '10.41.166.213', 'JUPYTER_934284_7119739_PORT_8888_TCP': 'tcp://10.41.58.249:8888', 'JUPYTER_3855592_7060744_PORT_8888_TCP_PORT': '8888', 'JUPYTER_6031435_7167894_PORT_8888_TCP_ADDR': '10.41.212.61', 'JUPYTER_6026042_7168048_SERVICE_HOST': '10.41.15.186', 'JUPYTER_4494484_7155238_PORT_8888_TCP': 'tcp://10.41.121.85:8888', 'JUPYTER_710848_7018590_PORT_8888_TCP': 'tcp://10.41.60.3
LAUNCH INFO 2023-11-29 09:42:05,103 ------------------------- ERROR LOG DETAIL -------------------------
loading annotations into memory...
Done (t=0.18s)
creating index...
index created!
[11/29 09:41:15] ppdet.data.source.coco INFO: Load [13887 samples valid, 0 samples invalid] in file work/tile/annotations/train_annos_own.json.
W1129 09:41:15.068631  2684 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 12.0, Runtime API Version: 11.2
W1129 09:41:15.074558  2684 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File "PaddleYOLO/tools/train.py", line 198, in <module>
    main()
  File "PaddleYOLO/tools/train.py", line 194, in main
    run(FLAGS, cfg)
  File "PaddleYOLO/tools/train.py", line 147, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleYOLO/ppdet/engine/trainer.py", line 434, in train
    outputs = model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/architectures/meta_arch.py", line 60, in forward
    out = self.get_loss()
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/architectures/yolov7.py", line 95, in get_loss
    return self._forward()
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/architectures/yolov7.py", line 77, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/heads/yolov7_head.py", line 220, in forward
    return self.loss(yolo_outputs, targets, self.anchors)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/losses/yolov7_loss.py", line 175, in forward
    n = b.shape[0]  # number of targets
AttributeError: 'list' object has no attribute 'shape'
LAUNCH INFO 2023-11-29 09:42:05,104 Exit code 1

### 复现环境 Environment

在AIstudio上运行，
<img width="307" alt="image" src="https://github.com/PaddlePaddle/PaddleYOLO/assets/24787488/92703462-5032-48a6-89c5-33738521aacf">

### Bug描述确认 Bug description confirmation

- [ ] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
请升级paddle版本，推荐2.5以上

**Comment by jiangming7301** [comment]
![image](https://github.com/PaddlePaddle/PaddleYOLO/assets/24787488/7550eb1a-9876-4119-83f1-6863ce2b954b)
还是报错：
LAUNCH INFO 2023-11-29 20:17:38,380 -----------  Configuration  ----------------------
[2023-11-29 20:17:38,380] [    INFO] __init__.py:43 - -----------  Configuration  ----------------------
LAUNCH INFO 2023-11-29 20:17:38,380 auto_parallel_config: None
[2023-11-29 20:17:38,380] [    INFO] __init__.py:45 - auto_parallel_config: None
LAUNCH INFO 2023-11-29 20:17:38,380 devices: None
[2023-11-29 20:17:38,380] [    INFO] __init__.py:45 - devices: None
LAUNCH INFO 2023-11-29 20:17:38,380 elastic_level: -1
[2023-11-29 20:17:38,380] [    INFO] __init__.py:45 - elastic_level: -1
LAUNCH INFO 2023-11-29 20:17:38,380 elastic_timeout: 30
[2023-11-29 20:17:38,380] [    INFO] __init__.py:45 - elastic_timeout: 30
LAUNCH INFO 2023-11-29 20:17:38,380 gloo_port: 6767
[2023-11-29 20:17:38,380] [    INFO] __init__.py:45 - gloo_port: 6767
LAUNCH INFO 2023-11-29 20:17:38,380 host: None
[2023-11-29 20:17:38,380] [    INFO] __init__.py:45 - host: None
LAUNCH INFO 2023-11-29 20:17:38,380 ips: None
[2023-11-29 20:17:38,380] [    INFO] __init__.py:45 - ips: None
LAUNCH INFO 2023-11-29 20:17:38,381 job_id: default
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - job_id: default
LAUNCH INFO 2023-11-29 20:17:38,381 legacy: False
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - legacy: False
LAUNCH INFO 2023-11-29 20:17:38,381 log_dir: log
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - log_dir: log
LAUNCH INFO 2023-11-29 20:17:38,381 log_level: INFO
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - log_level: INFO
LAUNCH INFO 2023-11-29 20:17:38,381 log_overwrite: False
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - log_overwrite: False
LAUNCH INFO 2023-11-29 20:17:38,381 master: None
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - master: None
LAUNCH INFO 2023-11-29 20:17:38,381 max_restart: 3
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - max_restart: 3
LAUNCH INFO 2023-11-29 20:17:38,381 nnodes: 1
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - nnodes: 1
LAUNCH INFO 2023-11-29 20:17:38,381 nproc_per_node: None
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - nproc_per_node: None
LAUNCH INFO 2023-11-29 20:17:38,381 rank: -1
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - rank: -1
LAUNCH INFO 2023-11-29 20:17:38,381 run_mode: collective
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - run_mode: collective
LAUNCH INFO 2023-11-29 20:17:38,381 server_num: None
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - server_num: None
LAUNCH INFO 2023-11-29 20:17:38,381 servers: 
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - servers: 
LAUNCH INFO 2023-11-29 20:17:38,381 start_port: 6070
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - start_port: 6070
LAUNCH INFO 2023-11-29 20:17:38,381 trainer_num: None
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - trainer_num: None
LAUNCH INFO 2023-11-29 20:17:38,381 trainers: 
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - trainers: 
LAUNCH INFO 2023-11-29 20:17:38,381 training_script: PaddleYOLO/tools/train.py
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - training_script: PaddleYOLO/tools/train.py
LAUNCH INFO 2023-11-29 20:17:38,381 training_script_args: ['-c', 'configs_yolo7/yolov7_tiny_300e_coco.yml', '--use_vdl=True', '-o', 'worker_num=4', '--eval']
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - training_script_args: ['-c', 'configs_yolo7/yolov7_tiny_300e_coco.yml', '--use_vdl=True', '-o', 'worker_num=4', '--eval']
LAUNCH INFO 2023-11-29 20:17:38,381 with_gloo: 1
[2023-11-29 20:17:38,381] [    INFO] __init__.py:45 - with_gloo: 1
LAUNCH INFO 2023-11-29 20:17:38,381 --------------------------------------------------
[2023-11-29 20:17:38,381] [    INFO] __init__.py:46 - --------------------------------------------------
LAUNCH INFO 2023-11-29 20:17:38,382 Job: default, mode collective, replicas 1[1:1], elastic False
[2023-11-29 20:17:38,382] [    INFO] controller.py:176 - Job: default, mode collective, replicas 1[1:1], elastic False
LAUNCH INFO 2023-11-29 20:17:38,385 Run Pod: eqdgru, replicas 1, status ready
[2023-11-29 20:17:38,385] [    INFO] controller.py:62 - Run Pod: eqdgru, replicas 1, status ready
LAUNCH INFO 2023-11-29 20:17:38,413 Watching Pod: eqdgru, replicas 1, status running
[2023-11-29 20:17:38,413] [    INFO] controller.py:86 - Watching Pod: eqdgru, replicas 1, status running
======================= Modified FLAGS detected =======================
FLAGS(name='FLAGS_selected_gpus', current_value='0', default_value='')
=======================================================================
loading annotations into memory...
Done (t=0.10s)
creating index...
index created!
[11/29 20:17:41] ppdet.data.source.coco INFO: Load [13887 samples valid, 0 samples invalid] in file work/tile/annotations/train_annos_own.json.
W1129 20:17:41.240366   540 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 12.0, Runtime API Version: 11.8
W1129 20:17:41.242010   540 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
Traceback (most recent call last):
  File "/home/aistudio/PaddleYOLO/tools/train.py", line 198, in <module>
    main()
  File "/home/aistudio/PaddleYOLO/tools/train.py", line 194, in main
    run(FLAGS, cfg)
  File "/home/aistudio/PaddleYOLO/tools/train.py", line 147, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleYOLO/ppdet/engine/trainer.py", line 434, in train
    outputs = model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/architectures/meta_arch.py", line 60, in forward
    out = self.get_loss()
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/architectures/yolov7.py", line 95, in get_loss
    return self._forward()
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/architectures/yolov7.py", line 77, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/heads/yolov7_head.py", line 220, in forward
    return self.loss(yolo_outputs, targets, self.anchors)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/losses/yolov7_loss.py", line 175, in forward
    n = b.shape[0]  # number of targets
AttributeError: 'list' object has no attribute 'shape'
LAUNCH INFO 2023-11-29 20:18:32,463 Pod failed
[2023-11-29 20:18:32,463] [    INFO] controller.py:115 - Pod failed
LAUNCH ERROR 2023-11-29 20:18:32,464 Container failed !!!
Container rank 0 status failed cmd ['/opt/conda/envs/python35-paddle120-env/bin/python', '-u', 'PaddleYOLO/tools/train.py', '-c', 'configs_yolo7/yolov7_tiny_300e_coco.yml', '--use_vdl=True', '-o', 'worker_num=4', '--eval'] code 1 log log/workerlog.0 
env {'SHELL': '/bin/bash', 'STUDIO_SERVING_URL_TEMPLATE': 'https://aistudio.baidu.com/application/detail/{}', 'JUPYTER_7207170_7173349_PORT_8888_TCP_ADDR': '10.41.214.141', 'JUPYTER_2862833_6737614_PORT_8888_TCP_PROTO': 'tcp', 'JUPYTER_1949767_5855869_PORT': 'tcp://10.41.118.26:8888', 'JUPYTER_2858305_6542390_PORT_8888_TCP_ADDR': '10.41.74.82', 'JUPYTER_990707_7072718_SERVICE_PORT': '8888', 'JUPYTER_7641412_7158646_PORT': 'tcp://10.41.196.107:8888', 'JUPYTER_7646910_7169624_PORT': 'tcp://10.41.37.63:8888', 'JUPYTER_3934698_7082253_SERVICE_HOST': '10.41.164.222', 'JUPYTER_7362483_7121438_SERVICE_HOST': '10.41.107.121', 'JUPYTER_6113036_7115017_PORT_8888_TCP_PROTO': 'tcp', 'NV_LIBCUBLAS_VERSION': '11.11.3.6-1', 'NVIDIA_VISIBLE_DEVICES': 'all', 'JUPYTER_3769568_7173534_PORT_8888_TCP_ADDR': '10.41.72.226', 'KUBERNETES_SERVICE_PORT_HTTPS': '443', 'JUPYTER_6568462_7173461_PORT_8888_TCP_PROTO': 'tcp', 'JUPYTER_7696903_7173419_PORT_8888_TCP_PORT': '8888', 'JUPYTER_4218454_7166329_PORT_8888_TCP
[2023-11-29 20:18:32,464] [   ERROR] controller.py:116 - Container failed !!!
Container rank 0 status failed cmd ['/opt/conda/envs/python35-paddle120-env/bin/python', '-u', 'PaddleYOLO/tools/train.py', '-c', 'configs_yolo7/yolov7_tiny_300e_coco.yml', '--use_vdl=True', '-o', 'worker_num=4', '--eval'] code 1 log log/workerlog.0 
env {'SHELL': '/bin/bash', 'STUDIO_SERVING_URL_TEMPLATE': 'https://aistudio.baidu.com/application/detail/{}', 'JUPYTER_7207170_7173349_PORT_8888_TCP_ADDR': '10.41.214.141', 'JUPYTER_2862833_6737614_PORT_8888_TCP_PROTO': 'tcp', 'JUPYTER_1949767_5855869_PORT': 'tcp://10.41.118.26:8888', 'JUPYTER_2858305_6542390_PORT_8888_TCP_ADDR': '10.41.74.82', 'JUPYTER_990707_7072718_SERVICE_PORT': '8888', 'JUPYTER_7641412_7158646_PORT': 'tcp://10.41.196.107:8888', 'JUPYTER_7646910_7169624_PORT': 'tcp://10.41.37.63:8888', 'JUPYTER_3934698_7082253_SERVICE_HOST': '10.41.164.222', 'JUPYTER_7362483_7121438_SERVICE_HOST': '10.41.107.121', 'JUPYTER_6113036_7115017_PORT_8888_TCP_PROTO': 'tcp', 'NV_LIBCUBLAS_VERSION': '11.11.3.6-1', 'NVIDIA_VISIBLE_DEVICES': 'all', 'JUPYTER_3769568_7173534_PORT_8888_TCP_ADDR': '10.41.72.226', 'KUBERNETES_SERVICE_PORT_HTTPS': '443', 'JUPYTER_6568462_7173461_PORT_8888_TCP_PROTO': 'tcp', 'JUPYTER_7696903_7173419_PORT_8888_TCP_PORT': '8888', 'JUPYTER_4218454_7166329_PORT_8888_TCP
LAUNCH INFO 2023-11-29 20:18:32,479 ------------------------- ERROR LOG DETAIL -------------------------
[2023-11-29 20:18:32,479] [    INFO] controller.py:117 - ------------------------- ERROR LOG DETAIL -------------------------
======================= Modified FLAGS detected =======================
FLAGS(name='FLAGS_selected_gpus', current_value='0', default_value='')
=======================================================================
loading annotations into memory...
Done (t=0.10s)
creating index...
index created!
[11/29 20:17:41] ppdet.data.source.coco INFO: Load [13887 samples valid, 0 samples invalid] in file work/tile/annotations/train_annos_own.json.
W1129 20:17:41.240366   540 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 12.0, Runtime API Version: 11.8
W1129 20:17:41.242010   540 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
Traceback (most recent call last):
  File "/home/aistudio/PaddleYOLO/tools/train.py", line 198, in <module>
    main()
  File "/home/aistudio/PaddleYOLO/tools/train.py", line 194, in main
    run(FLAGS, cfg)
  File "/home/aistudio/PaddleYOLO/tools/train.py", line 147, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleYOLO/ppdet/engine/trainer.py", line 434, in train
    outputs = model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/architectures/meta_arch.py", line 60, in forward
    out = self.get_loss()
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/architectures/yolov7.py", line 95, in get_loss
    return self._forward()
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/architectures/yolov7.py", line 77, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/heads/yolov7_head.py", line 220, in forward
    return self.loss(yolo_outputs, targets, self.anchors)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/losses/yolov7_loss.py", line 175, in forward
    n = b.shape[0]  # number of targets
AttributeError: 'list' object has no attribute 'shape'
LAUNCH INFO 2023-11-29 20:18:32,479 Exit code 1
[2023-11-29 20:18:32,479] [    INFO] controller.py:149 - Exit code 1

**Comment by jiangming7301** [comment]
?

**Comment by nemonameless** [comment]
谢谢建议，后续会进行下排查修复。

**Comment by nemonameless** [comment]
您好，现在develop分支代码已经没有这个问题，已用paddle2.5.2实测过，内部也在训着用的。谢谢。
