### ISSUE TITLE
rtdetr评估报错

### ISSUE THREAD

**Issue by ilovefanjian** [PaddlePaddle/PaddleYOLO#219]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

rtdetr_r18模型边训练边评估，评估时报错Traceback (most recent call last):
  File "tools/train.py", line 198, in <module>
    main()
  File "tools/train.py", line 194, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 147, in run
    trainer.train(FLAGS.eval)
  File "E:\PaddleYOLO-develop\ppdet\engine\trainer.py", line 496, in train
    self._eval_with_loader(self._eval_loader)
  File "E:\PaddleYOLO-develop\ppdet\engine\trainer.py", line 533, in _eval_with_loader
    outs = self.model(data)
  File "D:\anaconda\A\envs\pd\lib\site-packages\paddle\nn\layer\layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "E:\PaddleYOLO-develop\ppdet\modeling\architectures\meta_arch.py", line 76, in forward
    outs.append(self.get_pred())
  File "E:\PaddleYOLO-develop\ppdet\modeling\architectures\detr.py", line 116, in get_pred
    return self._forward()
  File "E:\PaddleYOLO-develop\ppdet\modeling\architectures\detr.py", line 103, in _forward
    bbox, bbox_num, mask = self.post_process(
AttributeError: 'tuple' object has no attribute 'shape'

**Comment by nemonameless** [comment]
已修复。https://github.com/PaddlePaddle/PaddleYOLO/commit/eb41a651e548bcc278342d0316442b43884d0b64
