### ISSUE TITLE
yolov7的head和数据增强换成ppyoloe之后训练Loss上涨且不能评估测试集

### ISSUE THREAD

**Issue by NwTbbetter** [PaddlePaddle/PaddleYOLO#22]
为啥把yolov7的head和数据增强换成ppyoloe之后，会出现这样的问题？
![image](https://user-images.githubusercontent.com/99952437/188812395-377e62b3-04e9-4b44-91f5-fe45710b0eee.png)

### 复现环境 Environment

- paddle:2.3.1
- python:3.7.13

**Comment by NwTbbetter** [comment]
就很奇怪，不改数据增强会因为没有gt_meta['pad_gt_mask']报错，改了数据增强，会报这样的错误，然后我给to_tensor了之后就是上面的，啥也学不到。
```
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/home/yaozhuohan/bxy/PaddleDetection_YOLOSeries/ppdet/engine/trainer.py", line 514, in train
    outputs = model(data)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/yaozhuohan/bxy/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/home/yaozhuohan/bxy/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/yolov5.py", line 98, in get_loss
    return self._forward()
  File "/home/yaozhuohan/bxy/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/yolov5.py", line 88, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/yaozhuohan/bxy/PaddleDetection_YOLOSeries/ppdet/modeling/heads/ppyoloe_head.py", line 220, in forward
    return self.forward_train(feats, targets)
  File "/home/yaozhuohan/bxy/PaddleDetection_YOLOSeries/ppdet/modeling/heads/ppyoloe_head.py", line 165, in forward_train
    ], targets)
  File "/home/yaozhuohan/bxy/PaddleDetection_YOLOSeries/ppdet/modeling/heads/ppyoloe_head.py", line 322, in get_loss
    pred_bboxes=pred_bboxes.detach() * stride_tensor)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/yaozhuohan/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "/home/yaozhuohan/bxy/PaddleDetection_YOLOSeries/ppdet/modeling/assigners/atss_assigner.py", line 114, in forward
    assert gt_labels.ndim == gt_bboxes.ndim and \
AttributeError: 'list' object has no attribute 'ndim'
```

**Comment by nemonameless** [comment]
请按issue模板提问谢谢。
head的代码里会包括loss计算，每个YOLO的loss计算需要不同gt target的字段，是来自reader里构造的，建议理解了之后再改。
1个epoch总共只有17个iter这种数据集实在太小了，估计你GPU资源也不够用总bs也很小，这种小数据集没有预训练很难训收敛的。你拼装的模型要训小数据集，起码要加载backbone的预训练。训练语句后面加上`-o pretrain_weights=https://bj.bcebos.com/v1/paddledet/models/yolov7_tiny_300e_coco.pdparams`，会报head里的权重对应不上warning是正常的不用管。

**Comment by NwTbbetter** [comment]
> 请按issue模板提问谢谢。 head的代码里会包括loss计算，每个YOLO的loss计算需要不同gt target的字段，是来自reader里构造的，建议理解了之后再改。 1个epoch总共只有17个iter这种数据集实在太小了，估计你GPU资源也不够用总bs也很小，这种小数据集没有预训练很难训收敛的。你拼装的模型要训小数据集，起码要加载backbone的预训练。训练语句后面加上`-o pretrain_weights=https://bj.bcebos.com/v1/paddledet/models/yolov7_tiny_300e_coco.pdparams`，会报head里的权重对应不上warning是正常的不用管。

好嘞谢谢~n那我这里用ppyoloe训练为什么也会出现这样的问题？ppyoloe不是在配置文件里加载预训练权重了嘛
![image](https://user-images.githubusercontent.com/99952437/188937359-7c5fec08-8b94-4d61-9185-c2fbafb323f9.png)

**Comment by nemonameless** [comment]
是不是开了amp训的？ppyoloe amp训在某些版本的paddle上有问题，建议不开amp或换paddle2.2.2去专门训ppyoloe的amp

**Comment by NwTbbetter** [comment]
> 是不是开了amp训的？ppyoloe amp训在某些版本的paddle上有问题，建议不开amp或换paddle2.2.2去专门训ppyoloe的amp

好嘞我再试一下，这个bug是不是得修复一下呀？还有ppyoloe开了print_flops也会报错，直接不能跑了

**Comment by nemonameless** [comment]
amp问题在paddle develop版本修复了，但是编的包可能滞后。print_flops需要是单尺度下的，reader里改成单尺度640x640就行。
