### ISSUE TITLE
On export, KeyError: 'name'

### ISSUE THREAD

**Issue by rlewkowicz** [PaddlePaddle/PaddleYOLO#243]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Export

### Bug描述 Describe the Bug

```
PS C:\Repos\ultralytics\yolov10\PaddleYOLO> python tools/export_model.py -c configs/yolov10/yolov10_s_500e_coco.yml -o weights=output/yolov10_s_500e_coco/best_model.pdparams
Traceback (most recent call last):
  File "C:\Repos\ultralytics\yolov10\PaddleYOLO\tools\export_model.py", line 107, in <module>
    main()
  File "C:\Repos\ultralytics\yolov10\PaddleYOLO\tools\export_model.py", line 103, in main
    run(FLAGS, cfg)
  File "C:\Repos\ultralytics\yolov10\PaddleYOLO\tools\export_model.py", line 64, in run
    trainer = Trainer(cfg, mode='test')
  File "C:\Repos\ultralytics\yolov10\PaddleYOLO\ppdet\engine\trainer.py", line 195, in __init__
    self.dataset = self.cfg['{}Dataset'.format(capital_mode)] = create(
  File "C:\Repos\ultralytics\yolov10\PaddleYOLO\ppdet\core\workspace.py", line 292, in create
    return cls(**cls_kwargs)
  File "C:\Repos\ultralytics\yolov10\PaddleYOLO\ppdet\data\source\dataset.py", line 278, in __init__
    type = dataset_args.pop("name")
KeyError: 'name'
```

### 复现环境 Environment

```
OS                  Windows-11
Environment         Windows
Python              3.10.9
```

```
paddle2onnx                    1.0.6
paddledet                      2.6.0                c:\repos\ultralytics\yolov10\paddleyolo
paddlepaddle                   2.6.1
paddlepaddle-gpu               2.6.1
```

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by rlewkowicz** [comment]
This was me. I removed Test from the yml thinking I could get by without.
