### ISSUE TITLE
yolov7训练自定义数据集到一定数量的epoch会报错shape concat不匹配和IndexError

### ISSUE THREAD

**Issue by WKangei** [PaddlePaddle/PaddleYOLO#25]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

python tools/train.py -c configs/yolov7/yolov7_l_300e_coco.yml --eval
修改了数据集和batch_size=16，在单卡上训练的

Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/engine/trainer.py", line 535, in train
    outputs = model(data)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/yolov5.py", line 98, in get_loss
    return self._forward()
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/yolov5.py", line 84, in _forward
    body_feats = self.backbone(self.inputs)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/backbones/csp_darknet.py", line 1003, in forward
    x = layer(x)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/container.py", line 98, in forward
    input = layer(input)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/backbones/csp_darknet.py", line 546, in forward
    x = paddle.concat([x_2, x_1], axis=1)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 331, in concat
    return paddle.fluid.layers.concat(input=x, axis=axis, name=name)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/layers/tensor.py", line 343, in concat
    _C_ops.concat(input, out, 'axis', axis)
ValueError: (InvalidArgument) The 2-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [16, 256, 45, 45], input[1]'s shape = [16, 256, 44, 44].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:45 != inputs_dims[i][j]:44.] (at /paddle/paddle/phi/kernels/funcs/concat_funcs.h:83)
  [operator < concat > error]

**Comment by nemonameless** [comment]
报bug请按issue模板提问谢谢。
是不是还改了原本的输入尺度640为720或360了？还是改成了多尺度训练？输入尺度必须是32的整数倍。
原版L模型是总bs=256训的，一个GPU的bs=16这种配置总bs太小了，训的精度不会很高。

**Comment by WKangei** [comment]
> 报bug请按issue模板提问谢谢。 是不是还改了原本的输入尺度640为720或360了？还是改成了多尺度训练？输入尺度必须是32的整数倍。 原版L模型是总bs=256训的，一个GPU的bs=16这种配置总bs太小了，训的精度不会很高。

好的，我以为这是一个问题，之后会注意。
没有修改输入尺度，是640，还有就是关闭一些数据增强的功能
MosaicPerspective: {target_size: *input_size, mosaic_prob: 0.0, mixup_prob: 0.0, paste_in_prob: 0.15, translate: 0.2, scale: 0.9}
精度问题由于算力问题，只能单卡，修改了base_lr: 0.00125，想先看下效果，训练好几次都是中间报错了。

**Comment by nemonameless** [comment]
640输入尺度网络中的特征层应该不会出现45x45这种数值的因为不整除。确定前几个epoch是可以训且有具体的mAP结果吗？到报错为止上面的loss的日志也请发下。

**Comment by WKangei** [comment]
[09/13 16:24:28] ppdet.engine INFO: Eval iter: 0
[09/13 16:24:31] ppdet.metrics.metrics INFO: Accumulating evaluatation results...
[09/13 16:24:31] ppdet.metrics.metrics INFO: mAP(0.50, integral) = 3.95%
[09/13 16:24:31] ppdet.engine INFO: Total sample number: 100, averge FPS: 29.075971726672122
[09/13 16:24:31] ppdet.engine INFO: Best test bbox ap is 0.040.
[09/13 16:24:33] ppdet.utils.checkpoint INFO: Save checkpoint: output/yolov7_l_300e_coco
[09/13 16:24:34] ppdet.engine INFO: Epoch: [270] [0/7] learning_rate: 0.000241 loss_box: 0.028128 loss_obj: 0.007273 loss_cls: 0.000892 loss: 0.566398 eta: 6:19:37 batch_cost: 1.1859 data_cost: 0.2223 ips: 13.4916 images/s
[09/13 16:24:44] ppdet.engine INFO: Epoch: [271] [0/7] learning_rate: 0.000237 loss_box: 0.028097 loss_obj: 0.007273 loss_cls: 0.000901 loss: 0.566265 eta: 6:19:35 batch_cost: 1.1955 data_cost: 0.2335 ips: 13.3841 images/s
[09/13 16:24:54] ppdet.engine INFO: Epoch: [272] [0/7] learning_rate: 0.000234 loss_box: 0.027968 loss_obj: 0.007224 loss_cls: 0.000892 loss: 0.564950 eta: 6:19:31 batch_cost: 1.1929 data_cost: 0.2366 ips: 13.4132 images/s
[09/13 16:25:04] ppdet.engine INFO: Epoch: [273] [0/7] learning_rate: 0.000230 loss_box: 0.027910 loss_obj: 0.007224 loss_cls: 0.000892 loss: 0.563532 eta: 6:19:24 batch_cost: 1.1887 data_cost: 0.2375 ips: 13.4604 images/s
[09/13 16:25:13] ppdet.engine INFO: Epoch: [274] [0/7] learning_rate: 0.000226 loss_box: 0.027910 loss_obj: 0.007224 loss_cls: 0.000892 loss: 0.565121 eta: 6:19:14 batch_cost: 1.1851 data_cost: 0.2340 ips: 13.5009 images/s
[09/13 16:25:23] ppdet.engine INFO: Epoch: [275] [0/7] learning_rate: 0.000222 loss_box: 0.027847 loss_obj: 0.007201 loss_cls: 0.000882 loss: 0.563532 eta: 6:19:03 batch_cost: 1.2050 data_cost: 0.2465 ips: 13.2782 images/s
[09/13 16:25:32] ppdet.engine INFO: Epoch: [276] [0/7] learning_rate: 0.000219 loss_box: 0.027781 loss_obj: 0.007224 loss_cls: 0.000890 loss: 0.562847 eta: 6:18:57 batch_cost: 1.2080 data_cost: 0.2463 ips: 13.2452 images/s
[09/13 16:25:42] ppdet.engine INFO: Epoch: [277] [0/7] learning_rate: 0.000215 loss_box: 0.027994 loss_obj: 0.007224 loss_cls: 0.000892 loss: 0.562847 eta: 6:18:49 batch_cost: 1.2076 data_cost: 0.2425 ips: 13.2491 images/s
[09/13 16:25:51] ppdet.engine INFO: Epoch: [278] [0/7] learning_rate: 0.000211 loss_box: 0.027463 loss_obj: 0.007224 loss_cls: 0.000890 loss: 0.558018 eta: 6:18:41 batch_cost: 1.2079 data_cost: 0.2451 ips: 13.2463 images/s
[09/13 16:26:02] ppdet.engine INFO: Epoch: [279] [0/7] learning_rate: 0.000208 loss_box: 0.027206 loss_obj: 0.007286 loss_cls: 0.000885 loss: 0.554306 eta: 6:18:37 batch_cost: 1.2124 data_cost: 0.2482 ips: 13.1968 images/s
[09/13 16:26:09] ppdet.utils.checkpoint INFO: Save checkpoint: output/yolov7_l_300e_coco
[09/13 16:26:09] ppdet.engine INFO: Eval iter: 0
[09/13 16:26:13] ppdet.metrics.metrics INFO: Accumulating evaluatation results...
[09/13 16:26:13] ppdet.metrics.metrics INFO: mAP(0.50, integral) = 3.87%
[09/13 16:26:13] ppdet.engine INFO: Total sample number: 100, averge FPS: 28.664333410513212
[09/13 16:26:13] ppdet.engine INFO: Best test bbox ap is 0.040.
[09/13 16:26:15] ppdet.engine INFO: Epoch: [280] [0/7] learning_rate: 0.000204 loss_box: 0.027119 loss_obj: 0.007356 loss_cls: 0.000879 loss: 0.552302 eta: 6:18:19 batch_cost: 1.2006 data_cost: 0.2287 ips: 13.3271 images/s
[09/13 16:26:25] ppdet.engine INFO: Epoch: [281] [0/7] learning_rate: 0.000200 loss_box: 0.026897 loss_obj: 0.007335 loss_cls: 0.000888 loss: 0.549441 eta: 6:18:13 batch_cost: 1.1988 data_cost: 0.2337 ips: 13.3468 images/s
[09/13 16:26:34] ppdet.engine INFO: Epoch: [282] [0/7] learning_rate: 0.000196 loss_box: 0.026543 loss_obj: 0.007286 loss_cls: 0.000888 loss: 0.548907 eta: 6:18:05 batch_cost: 1.1986 data_cost: 0.2351 ips: 13.3490 images/s
[09/13 16:26:44] ppdet.engine INFO: Epoch: [283] [0/7] learning_rate: 0.000193 loss_box: 0.026288 loss_obj: 0.007305 loss_cls: 0.000879 loss: 0.548583 eta: 6:17:56 batch_cost: 1.1945 data_cost: 0.2278 ips: 13.3943 images/s
[09/13 16:26:54] ppdet.engine INFO: Epoch: [284] [0/7] learning_rate: 0.000189 loss_box: 0.026260 loss_obj: 0.007356 loss_cls: 0.000888 loss: 0.545720 eta: 6:17:51 batch_cost: 1.1925 data_cost: 0.2189 ips: 13.4171 images/s
[09/13 16:27:03] ppdet.engine INFO: Epoch: [285] [0/7] learning_rate: 0.000185 loss_box: 0.026236 loss_obj: 0.007364 loss_cls: 0.000899 loss: 0.547612 eta: 6:17:43 batch_cost: 1.2151 data_cost: 0.2356 ips: 13.1677 images/s
[09/13 16:27:13] ppdet.engine INFO: Epoch: [286] [0/7] learning_rate: 0.000181 loss_box: 0.026220 loss_obj: 0.007364 loss_cls: 0.000895 loss: 0.544005 eta: 6:17:40 batch_cost: 1.2141 data_cost: 0.2323 ips: 13.1781 images/s
[09/13 16:27:22] ppdet.engine INFO: Epoch: [287] [0/7] learning_rate: 0.000177 loss_box: 0.026220 loss_obj: 0.007388 loss_cls: 0.000895 loss: 0.544777 eta: 6:17:29 batch_cost: 1.2071 data_cost: 0.2195 ips: 13.2548 images/s
[09/13 16:27:32] ppdet.engine INFO: Epoch: [288] [0/7] learning_rate: 0.000174 loss_box: 0.026023 loss_obj: 0.007388 loss_cls: 0.000882 loss: 0.544005 eta: 6:17:21 batch_cost: 1.2058 data_cost: 0.2193 ips: 13.2694 images/s
[09/13 16:27:42] ppdet.engine INFO: Epoch: [289] [0/7] learning_rate: 0.000170 loss_box: 0.025880 loss_obj: 0.007388 loss_cls: 0.000895 loss: 0.542804 eta: 6:17:15 batch_cost: 1.2104 data_cost: 0.2256 ips: 13.2190 images/s
[09/13 16:27:49] ppdet.utils.checkpoint INFO: Save checkpoint: output/yolov7_l_300e_coco
[09/13 16:27:49] ppdet.engine INFO: Eval iter: 0
[09/13 16:27:53] ppdet.metrics.metrics INFO: Accumulating evaluatation results...
[09/13 16:27:53] ppdet.metrics.metrics INFO: mAP(0.50, integral) = 3.82%
[09/13 16:27:53] ppdet.engine INFO: Total sample number: 100, averge FPS: 29.130331631108106
[09/13 16:27:53] ppdet.engine INFO: Best test bbox ap is 0.040.
[09/13 16:27:55] ppdet.engine INFO: Epoch: [290] [0/7] learning_rate: 0.000166 loss_box: 0.025850 loss_obj: 0.007400 loss_cls: 0.000897 loss: 0.542804 eta: 6:16:54 batch_cost: 1.1992 data_cost: 0.2132 ips: 13.3427 images/s
[09/13 16:28:05] ppdet.engine INFO: Epoch: [291] [0/7] learning_rate: 0.000163 loss_box: 0.025628 loss_obj: 0.007400 loss_cls: 0.000908 loss: 0.540414 eta: 6:16:49 batch_cost: 1.2003 data_cost: 0.2184 ips: 13.3296 images/s
[09/13 16:28:14] ppdet.engine INFO: Epoch: [292] [0/7] learning_rate: 0.000159 loss_box: 0.025527 loss_obj: 0.007454 loss_cls: 0.000886 loss: 0.535968 eta: 6:16:40 batch_cost: 1.1987 data_cost: 0.2174 ips: 13.3473 images/s
[09/13 16:28:24] ppdet.engine INFO: Epoch: [293] [0/7] learning_rate: 0.000155 loss_box: 0.025118 loss_obj: 0.007480 loss_cls: 0.000877 loss: 0.529180 eta: 6:16:31 batch_cost: 1.1993 data_cost: 0.2194 ips: 13.3407 images/s
[09/13 16:28:33] ppdet.engine INFO: Epoch: [294] [0/7] learning_rate: 0.000151 loss_box: 0.024970 loss_obj: 0.007466 loss_cls: 0.000884 loss: 0.527595 eta: 6:16:25 batch_cost: 1.1960 data_cost: 0.2217 ips: 13.3777 images/s
[09/13 16:28:43] ppdet.engine INFO: Epoch: [295] [0/7] learning_rate: 0.000148 loss_box: 0.024799 loss_obj: 0.007490 loss_cls: 0.000883 loss: 0.525932 eta: 6:16:20 batch_cost: 1.2099 data_cost: 0.2440 ips: 13.2240 images/s
[09/13 16:28:53] ppdet.engine INFO: Epoch: [296] [0/7] learning_rate: 0.000144 loss_box: 0.024651 loss_obj: 0.007510 loss_cls: 0.000884 loss: 0.519163 eta: 6:16:15 batch_cost: 1.2113 data_cost: 0.2382 ips: 13.2095 images/s
[09/13 16:29:03] ppdet.engine INFO: Epoch: [297] [0/7] learning_rate: 0.000140 loss_box: 0.024651 loss_obj: 0.007510 loss_cls: 0.000883 loss: 0.514832 eta: 6:16:12 batch_cost: 1.2169 data_cost: 0.2484 ips: 13.1477 images/s
[09/13 16:29:13] ppdet.engine INFO: Epoch: [298] [0/7] learning_rate: 0.000136 loss_box: 0.024441 loss_obj: 0.007550 loss_cls: 0.000883 loss: 0.510028 eta: 6:16:06 batch_cost: 1.2194 data_cost: 0.2544 ips: 13.1214 images/s
[09/13 16:29:22] ppdet.engine INFO: Epoch: [299] [0/7] learning_rate: 0.000133 loss_box: 0.024408 loss_obj: 0.007510 loss_cls: 0.000862 loss: 0.509380 eta: 6:15:55 batch_cost: 1.2138 data_cost: 0.2517 ips: 13.1816 images/s
[09/13 16:29:30] ppdet.utils.checkpoint INFO: Save checkpoint: output/yolov7_l_300e_coco
[09/13 16:29:30] ppdet.engine INFO: Eval iter: 0
[09/13 16:29:33] ppdet.metrics.metrics INFO: Accumulating evaluatation results...
[09/13 16:29:33] ppdet.metrics.metrics INFO: mAP(0.50, integral) = 3.98%
[09/13 16:29:33] ppdet.engine INFO: Total sample number: 100, averge FPS: 28.703084824196768
[09/13 16:29:33] ppdet.engine INFO: Best test bbox ap is 0.040.
[09/13 16:29:35] ppdet.utils.checkpoint INFO: Save checkpoint: output/yolov7_l_300e_coco
[09/13 16:29:37] ppdet.engine INFO: Epoch: [300] [0/7] learning_rate: 0.000133 loss_box: 0.024312 loss_obj: 0.007550 loss_cls: 0.000852 loss: 0.506345 eta: 6:15:27 batch_cost: 1.1911 data_cost: 0.2349 ips: 13.4332 images/s
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/engine/trainer.py", line 535, in train
    outputs = model(data)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()

**Comment by nemonameless** [comment]
加载coco预训练权重了吗，加载了不可能这么低，加载了可以一开始eval就很高，即使后面报错了模型也可以先用再慢慢排错。
参照 [自定义数据集训练 fintune训练](https://github.com/nemonameless/PaddleDetection_YOLOSeries#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%95%B0%E6%8D%AE%E9%9B%86%E8%AE%AD%E7%BB%83)

**Comment by WKangei** [comment]
加载了预训练权重，报了一些警告，是不是和我修改了num_classes有关。
```
[09/14 09:04:42] ppdet.utils.checkpoint INFO: The shape [255] in pretrained weight yolo_head.yolo_output.0.bias is unmatched with the shape [24] in model yolo_head.yolo_output.0.bias. And the weight yolo_head.yolo_output.0.bias will not be loaded
[09/14 09:04:42] ppdet.utils.checkpoint INFO: The shape [255, 256, 1, 1] in pretrained weight yolo_head.yolo_output.0.weight is unmatched with the shape [24, 256, 1, 1] in model yolo_head.yolo_output.0.weight. And the weight yolo_head.yolo_output.0.weight will not be loaded
[09/14 09:04:42] ppdet.utils.checkpoint INFO: The shape [255] in pretrained weight yolo_head.yolo_output.1.bias is unmatched with the shape [24] in model yolo_head.yolo_output.1.bias. And the weight yolo_head.yolo_output.1.bias will not be loaded
[09/14 09:04:42] ppdet.utils.checkpoint INFO: The shape [255, 512, 1, 1] in pretrained weight yolo_head.yolo_output.1.weight is unmatched with the shape [24, 512, 1, 1] in model yolo_head.yolo_output.1.weight. And the weight yolo_head.yolo_output.1.weight will not be loaded
[09/14 09:04:42] ppdet.utils.checkpoint INFO: The shape [255] in pretrained weight yolo_head.yolo_output.2.bias is unmatched with the shape [24] in model yolo_head.yolo_output.2.bias. And the weight yolo_head.yolo_output.2.bias will not be loaded
[09/14 09:04:42] ppdet.utils.checkpoint INFO: The shape [255, 1024, 1, 1] in pretrained weight yolo_head.yolo_output.2.weight is unmatched with the shape [24, 1024, 1, 1] in model yolo_head.yolo_output.2.weight. And the weight yolo_head.yolo_output.2.weight will not be loaded
```
训练了一会，又报了个新的错误
```
[09/14 09:12:42] ppdet.engine INFO: Epoch: [48] [0/7] learning_rate: 0.001074 loss_box: 0.082412 loss_obj: 0.004362 loss_cls: 0.058456 loss: 2.200696 eta: 6:44:16 batch_cost: 1.2079 data_cost: 0.2493 ips: 13.2456 images/s
[09/14 09:12:51] ppdet.engine INFO: Epoch: [49] [0/7] learning_rate: 0.001070 loss_box: 0.082661 loss_obj: 0.004325 loss_cls: 0.057679 loss: 2.185836 eta: 6:44:25 batch_cost: 1.2093 data_cost: 0.2503 ips: 13.2311 images/s
[09/14 09:12:59] ppdet.utils.checkpoint INFO: Save checkpoint: output/yolov7_l_300e_coco
[09/14 09:12:59] ppdet.engine INFO: Eval iter: 0
[09/14 09:13:02] ppdet.metrics.metrics INFO: Accumulating evaluatation results...
[09/14 09:13:03] ppdet.metrics.metrics INFO: mAP(0.50, integral) = 0.01%
[09/14 09:13:03] ppdet.engine INFO: Total sample number: 100, averge FPS: 27.448760464817678
[09/14 09:13:03] ppdet.engine INFO: Best test bbox ap is 0.000.
[09/14 09:13:05] ppdet.engine INFO: Epoch: [50] [0/7] learning_rate: 0.001066 loss_box: 0.082584 loss_obj: 0.004401 loss_cls: 0.051953 loss: 2.110728 eta: 6:43:07 batch_cost: 1.1922 data_cost: 0.2335 ips: 13.4209 images/s
[09/14 09:13:14] ppdet.engine INFO: Epoch: [51] [0/7] learning_rate: 0.001063 loss_box: 0.082516 loss_obj: 0.004325 loss_cls: 0.046910 loss: 2.039651 eta: 6:43:03 batch_cost: 1.1910 data_cost: 0.2334 ips: 13.4336 images/s
[09/14 09:13:24] ppdet.engine INFO: Epoch: [52] [0/7] learning_rate: 0.001059 loss_box: 0.082516 loss_obj: 0.004362 loss_cls: 0.045543 loss: 2.026678 eta: 6:43:13 batch_cost: 1.1919 data_cost: 0.2325 ips: 13.4241 images/s
[09/14 09:13:34] ppdet.engine INFO: Epoch: [53] [0/7] learning_rate: 0.001055 loss_box: 0.082275 loss_obj: 0.004362 loss_cls: 0.043423 loss: 1.981473 eta: 6:43:23 batch_cost: 1.1915 data_cost: 0.2268 ips: 13.4279 images/s
[09/14 09:13:44] ppdet.engine INFO: Epoch: [54] [0/7] learning_rate: 0.001051 loss_box: 0.082275 loss_obj: 0.004362 loss_cls: 0.039534 loss: 1.936494 eta: 6:43:38 batch_cost: 1.1927 data_cost: 0.2250 ips: 13.4147 images/s
[09/14 09:13:54] ppdet.engine INFO: Epoch: [55] [0/7] learning_rate: 0.001048 loss_box: 0.082067 loss_obj: 0.004416 loss_cls: 0.033467 loss: 1.825138 eta: 6:44:27 batch_cost: 1.2247 data_cost: 0.2499 ips: 13.0644 images/s
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/engine/trainer.py", line 535, in train
    outputs = model(data)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/yolov5.py", line 98, in get_loss
    return self._forward()
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/yolov5.py", line 88, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/heads/yolo_head.py", line 755, in forward
    return self.loss(yolo_outputs, targets, self.anchors)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/root/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/losses/yolo_loss.py", line 512, in forward
    bs, as_, gjs, gis, targets, anchors = self.build_targets(
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/losses/yolo_loss.py", line 694, in build_targets
    matching_matrix[gt_idx, pos_idx] = 1.0
IndexError: index 8391588393605373696 is out of bounds for axis 1 with size 9

```

**Comment by nemonameless** [comment]
加载预训练权重的问题，看[注意](https://github.com/nemonameless/PaddleDetection_YOLOSeries#fintune%E8%AE%AD%E7%BB%83)
IndexError 的问题，paddle版本请使用2.3.2

**Comment by WKangei** [comment]
paddle的版本是 paddlepaddle-gpu==2.3.2.post112

**Comment by nemonameless** [comment]
> paddle的版本是 paddlepaddle-gpu==2.3.2.post112

不开amp训试试，或者安装develop版本的[paddle](https://www.paddlepaddle.org.cn/install/quick/zh/2.0rc-linux-source?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html)

**Comment by WKangei** [comment]
没有开amp，然后安装了paddlepaddle-gpu==0.0.0.post112，报一个新错误
```
[09/16 11:03:43] ppdet.engine INFO: Epoch: [4] [ 0/13] learning_rate: 0.001239 loss_box: 0.080578 loss_obj: 0.065984 loss_cls: 0.394559 loss: 4.174908 eta: 8:44:56 batch_cost: 0.8087 data_cost: 0.0941 ips: 9.8927 images/s
[09/16 11:03:54] ppdet.engine INFO: Epoch: [5] [ 0/13] learning_rate: 0.001235 loss_box: 0.080900 loss_obj: 0.019418 loss_cls: 0.319379 loss: 3.566030 eta: 8:39:45 batch_cost: 0.8010 data_cost: 0.0912 ips: 9.9880 images/s
[09/16 11:04:05] ppdet.engine INFO: Epoch: [6] [ 0/13] learning_rate: 0.001231 loss_box: 0.080578 loss_obj: 0.007074 loss_cls: 0.293792 loss: 3.107439 eta: 8:38:29 batch_cost: 0.7993 data_cost: 0.0918 ips: 10.0089 images/s
[09/16 11:04:17] ppdet.engine INFO: Epoch: [7] [ 0/13] learning_rate: 0.001228 loss_box: 0.077955 loss_obj: 0.005625 loss_cls: 0.264051 loss: 2.729098 eta: 8:41:52 batch_cost: 0.8048 data_cost: 0.0957 ips: 9.9409 images/s
[09/16 11:04:27] ppdet.engine INFO: Epoch: [8] [ 0/13] learning_rate: 0.001224 loss_box: 0.077955 loss_obj: 0.005455 loss_cls: 0.234371 loss: 2.458987 eta: 8:34:32 batch_cost: 0.7895 data_cost: 0.0959 ips: 10.1335 images/s
[09/16 11:04:38] ppdet.engine INFO: Epoch: [9] [ 0/13] learning_rate: 0.001220 loss_box: 0.077352 loss_obj: 0.004717 loss_cls: 0.192038 loss: 2.112710 eta: 8:33:12 batch_cost: 0.7817 data_cost: 0.0951 ips: 10.2335 images/s
[09/16 11:04:49] ppdet.utils.checkpoint INFO: Save checkpoint: output/yolov7_l_300e_coco
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/engine/trainer.py", line 593, in train
    self._eval_with_loader(self._eval_loader)
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/engine/trainer.py", line 625, in _eval_with_loader
    outs = self.model(data)
  File "/root/anaconda3/envs/paddledet/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/yolov5.py", line 101, in get_pred
    return self._forward()
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/yolov5.py", line 92, in _forward
    bbox, bbox_num = self.yolo_head.post_process(
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/heads/yolo_head.py", line 811, in post_process
    bbox_pred, bbox_num, _ = self.nms(pred_bboxes, pred_scores)
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/layers.py", line 564, in __call__
    return ops.multiclass_nms(bboxes, score, **kwargs)
  File "/paddle/tmp/PaddleDetection_YOLOSeries/ppdet/modeling/ops.py", line 499, in multiclass_nms
    output, index, nms_rois_num = _C_ops.multiclass_nms3(bboxes, scores,
ValueError: (InvalidArgument) multiclass_nms3(): argument (position 4) must be double, but got str (at /paddle/paddle/fluid/pybind/op_function_common.cc:211)
```

**Comment by nemonameless** [comment]
请拉取一下最新develop分支代码

目前develop分支适用于paddle develop版本，其他分支建议使用paddle2.3.2
