### ISSUE TITLE
yolov7-x,yolov7-l训练到第9个epoch error

### ISSUE THREAD

**Issue by skycat88** [PaddlePaddle/PaddleYOLO#42]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Training

### Bug描述 Describe the Bug

linux paddle2.3.2容器环境下，运行
自己voc 标准格式的数据，开启amp，开启预训练，config只是改了数据，其他还没有动过

命令：CUDA_VISIBLE_DEVICES=0  python3.7 tools/train.py -c configs/yolov7/yolov7_l_300e_zykj.yml --amp -o pretrain_weights=https://paddledet.bj.bcebos.com/models/yolov7_l_300e_coco.pdparams
##################################################################
config.yml:

_BASE_: [
  **'../datasets/zykj_detection.yml',**
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov7_elannet.yml',
  '_base_/yolov7_reader.yml',
]
log_iter: 100
snapshot_epoch: 10
weights: output/yolov7_l_300e_coco/model_final

arch: L

TrainReader:
  batch_size: 32 # 一块3090显卡能几乎跑满，再大的模型或者batch显卡性能不够

##########################################################

[10/18 05:15:43] ppdet.engine INFO: Epoch: [6] [100/107] eta: 3 days, 5:00:56 lr: 0.009850 loss_box: 0.072392 loss_obj: 0.006819 loss_cls: 0.234330 loss: 10.098155 batch_cost: 7.9959 data_cost: 6.6045 ips: 4.0020 images/s
[10/18 05:17:18] ppdet.engine INFO: Epoch: [7] [  0/107] eta: 3 days, 5:21:48 lr: 0.009820 loss_box: 0.072360 loss_obj: 0.006701 loss_cls: 0.235074 loss: 10.109240 batch_cost: 8.8357 data_cost: 7.4409 ips: 3.6217 images/s
[10/18 05:31:33] ppdet.engine INFO: Epoch: [7] [100/107] eta: 3 days, 4:44:26 lr: 0.009820 loss_box: 0.071314 loss_obj: 0.007220 loss_cls: 0.217982 loss: 9.457106 batch_cost: 8.5153 data_cost: 7.0825 ips: 3.7580 images/s
[10/18 05:33:09] ppdet.engine INFO: Epoch: [8] [  0/107] eta: 3 days, 5:03:17 lr: 0.009790 loss_box: 0.070992 loss_obj: 0.007268 loss_cls: 0.219685 loss: 9.510744 batch_cost: 9.3629 data_cost: 7.9285 ips: 3.4178 images/s
[10/18 05:47:04] ppdet.engine INFO: Epoch: [8] [100/107] eta: 3 days, 4:17:59 lr: 0.009790 loss_box: 0.070877 loss_obj: 0.006961 loss_cls: 0.206957 loss: 9.059731 batch_cost: 8.3161 data_cost: 6.9136 ips: 3.8480 images/s
[10/18 05:48:40] ppdet.engine INFO: Epoch: [9] [  0/107] eta: 3 days, 4:34:15 lr: 0.009760 loss_box: 0.070877 loss_obj: 0.006922 loss_cls: 0.203878 loss: 9.042969 batch_cost: 9.1522 data_cost: 7.7467 ips: 3.4964 images/s
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/shiyy/PaddleYOLO/ppdet/engine/trainer.py", line 403, in train
    outputs = model(data)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/shiyy/PaddleYOLO/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/shiyy/PaddleYOLO/ppdet/modeling/architectures/yolov5.py", line 92, in get_loss
    return self._forward()
  File "/shiyy/PaddleYOLO/ppdet/modeling/architectures/yolov5.py", line 77, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/shiyy/PaddleYOLO/ppdet/modeling/heads/yolov7_head.py", line 206, in forward
    return self.loss(yolo_outputs, targets, self.anchors)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/shiyy/PaddleYOLO/ppdet/modeling/losses/yolov7_loss.py", line 119, in forward
    inputs, targets, gt_targets['image'], anchors)
  File "/shiyy/PaddleYOLO/ppdet/modeling/losses/yolov7_loss.py", line 300, in build_targets
    matching_matrix[gt_idx, pos_idx] = 1.0
IndexError: index 140613145985136 is out of bounds for axis 1 with size 9

### 复现环境 Environment

linux
paddle2.3.2，容器环境
cuda11.2

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
换paddle2.4试试，paddle2.3.2的amp可能有bug，不加amp也可以训下。对yolov7来说总bs=32还是太小了，即使加载了coco预训练，效果未必训的高。

**Comment by skycat88** [comment]
@nemonameless  
1、不加amp 训练，同样的环境训练，也会出现在训练8个左右epoch出现 同样错误，不知道这是什么原因

**Comment by skycat88** [comment]
@nemonameless 
1、我现在换成了yolov6-m 训练，查看是否还出现这个问题，因为应该不是amp导致的，
2、换paddle2.4,是指在我paddle 2.3.2容器环境内， 卸载之前的paddle,然后 pip install 吗？

**Comment by nemonameless** [comment]
建议你直接使用ppyoloe+，fintune自己数据集最重要的是加载超强的预训练权重。
容器只是提供了初始环境，后来的环境都可以自行配置，pip或conda都行。

**Comment by pwy1327347084** [comment]
> 换paddle2.4试试，paddle2.3.2的amp可能有bug，不加amp也可以训练下。对yolov7来说总bs=32还是太小了，就算训练了coco预加载，效果未必训练的高。

yolov7和yolov6都是必须得多卡训练吗？我看readme中写的是尽量多卡训练，总bs不低于64。我在ai studio 上训练yolov7和yolov6都是用的单卡，bs=32，效果都不如ppyolo。拿训练集其中几个图片给yolov7做预测，预测框都是低于0.5，或者是0.51那样，甚至都预测不出来，然而ppyolo却是正常的0.9左右，0.8那样。都能预测出来。

**Comment by nemonameless** [comment]
yolov7和yolov6的原模型本身总bs默认都是8卡每卡32总共256的，比这个总bs小太多的话都还需要调参主要是loss。且yolov5 v6 v7的数据增强参数众多如mosaic mixup hsv等也需要调参的，换个数据集参数就未必准。而ppyolo系列保持了最简单基础且复用性极强的数据增强。

**Comment by nemonameless** [comment]
建议最新代码再试试，voc数据集的各个模型配置示例都在这里： https://github.com/PaddlePaddle/PaddleYOLO/tree/release/2.5/configs/voc
或者直接尝试 ppyoloe+ 。yolov7 yolov6训练建议总bs都开很大，原文总bs都是8*32总共256级别的，总bs少于这个数值太多的训练其实意义都不大。

**Comment by pwy1327347084** [comment]
yolov5在自身做预测的时候可以同时输出图片和txt文件，请问ppyolov2这个可以吗,我想做到预测完图片之后再直接截取目标框并保存，我看网上有相对应的代码，但是需要生成预测的txt文件，在pytorch的yolov5中，他的检测文件detect.py中就有--save-txt这个指令，咱们想要得到这个指令，是需要自己额外增加代码还是已经有这类的指令了。
