### ISSUE TITLE
yolov7训练报错

### ISSUE THREAD

**Issue by mrljwlm** [PaddlePaddle/PaddleYOLO#59]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

```
[11/23 03:43:27] ppdet.engine INFO: Epoch: [0] [ 0/82] eta: 0:51:19 lr: 0.000000 loss_box: 0.133824 loss_obj: 5.553813 loss_cls: 0.000000 loss: 34.125824 batch_cost: 1.8780 data_cost: 0.0010 ips: 3.1949 images/s
Traceback (most recent call last):
  File "I:\DeepLearningSystem\PaddleYOLO\train.py", line 513, in <module>
    main()
  File "I:\DeepLearningSystem\PaddleYOLO\train.py", line 509, in main
    run(FLAGS, cfg, logger, infer_output)
  File "I:\DeepLearningSystem\PaddleYOLO\train.py", line 279, in run
    trainer.train(FLAGS.eval)
  File "I:\DeepLearningSystem\PaddleYOLO\ppdet\engine\trainer.py", line 403, in train
    outputs = model(data)
  File "C:\Program Files\Python\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Program Files\Python\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "I:\DeepLearningSystem\PaddleYOLO\ppdet\modeling\architectures\meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "I:\DeepLearningSystem\PaddleYOLO\ppdet\modeling\architectures\yolov5.py", line 92, in get_loss
    return self._forward()
  File "I:\DeepLearningSystem\PaddleYOLO\ppdet\modeling\architectures\yolov5.py", line 77, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "C:\Program Files\Python\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Program Files\Python\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "I:\DeepLearningSystem\PaddleYOLO\ppdet\modeling\heads\yolov7_head.py", line 205, in forward
    return self.loss(yolo_outputs + yolo_outputs_aux, targets,
  File "C:\Program Files\Python\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "C:\Program Files\Python\Python39\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "I:\DeepLearningSystem\PaddleYOLO\ppdet\modeling\losses\yolov7_loss.py", line 118, in forward
    bs, as_, gjs, gis, targets, anchors = self.build_targets(
  File "I:\DeepLearningSystem\PaddleYOLO\ppdet\modeling\losses\yolov7_loss.py", line 255, in build_targets
    pxyxys = paddle.concat(pxyxys, 0)
  File "C:\Program Files\Python\Python39\lib\site-packages\paddle\tensor\manipulation.py", line 345, in concat
    return paddle.fluid.layers.concat(input=x, axis=axis, name=name)
  File "C:\Program Files\Python\Python39\lib\site-packages\paddle\fluid\layers\tensor.py", line 327, in concat
    return _C_ops.concat(input, 'axis', axis)
ValueError: (InvalidArgument) concat(): argument 'X' (position 0) must be list of Tensors, but got empty list (at ..\paddle/fluid/pybind/op_function.h:848)

```
[yolov7_loss.py](https://github.com/PaddlePaddle/PaddleYOLO/blob/release/2.5/ppdet/modeling/losses/yolov7_loss.py)第255行，如果pxyxys为空会报错
```
            pxyxys, p_cls, p_obj = [], [], []
            from_which_layer = []
            all_b, all_a, all_gj, all_gi = [], [], [], []
            all_anch = []

            empty_feats_num = 0
            for i, pi in enumerate(p):
                idx = (indices[i][0] == batch_idx)
                if idx.sum() == 0:
                    empty_feats_num += 1
                    continue
                b, a, gj, gi = indices[i][0][idx], indices[i][1][idx], indices[
                    i][2][idx], indices[i][3][idx]
                all_b.append(b)
                all_a.append(a)
                all_gj.append(gj)
                all_gi.append(gi)
                all_anch.append(anch[i][idx])
                from_which_layer.append(paddle.ones([len(b)]) * i)

                fg_pred = pi[b, a, gj, gi]
                if len(fg_pred.shape) == 1:  # paddle2.3 index
                    fg_pred = fg_pred.unsqueeze(0)

                p_obj.append(fg_pred[:, 4:5])
                p_cls.append(fg_pred[:, 5:])

                grid = paddle.stack([gi, gj], 1)
                pxy = (F.sigmoid(fg_pred[:, :2]) * 2. - 0.5 + grid
                       ) * self.downsample_ratios[i]
                pwh = (F.sigmoid(fg_pred[:, 2:4]) *
                       2)**2 * anch[i][idx] * self.downsample_ratios[i]
                pxywh = paddle.concat([pxy, pwh], -1)
                pxyxy = self.xywh2xyxy(pxywh)
                pxyxys.append(pxyxy)

            if empty_feats_num == 3:  # note
                continue
            pxyxys = paddle.concat(pxyxys, 0)           #<----------------报错
            if pxyxys.shape[0] == 0:
                continue
```
前面应该增加一个判断条件判断pxyxys是否为空：
```
if len(pxyxys) == 0: 
    continue
```

### 复现环境 Environment

-windows
-paddle 2.2.2
-release 2.5
-cuda 11.2

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
你好，请先仔细阅读文档，yolov7推荐使用至少2.3.2以上的paddle版本，win请使用develop版本的paddle版本。
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html

**Comment by linhandev** [comment]
这个貌似2.3也有

**Comment by nemonameless** [comment]
> 这个貌似2.3也有

这个报错是因为paddle2.3以下的版本tensor索引问题，按文档推荐的版本安装就行。
