### ISSUE TITLE
训练错误

### ISSUE THREAD

**Issue by fanyuanxiang** [PaddlePaddle/PaddleYOLO#6]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleDetection_YOLOSeries/ppdet/engine/trainer.py", line 487, in train
    outputs = model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/home/aistudio/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/yolov5.py", line 98, in get_loss
    return self._forward()
  File "/home/aistudio/PaddleDetection_YOLOSeries/ppdet/modeling/architectures/yolov5.py", line 88, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection_YOLOSeries/ppdet/modeling/heads/yolo_head.py", line 727, in forward
    self.anchors)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection_YOLOSeries/ppdet/modeling/losses/yolo_loss.py", line 513, in forward
    inputs, targets, gt_targets['image'], anchors)
  File "/home/aistudio/PaddleDetection_YOLOSeries/ppdet/modeling/losses/yolo_loss.py", line 593, in build_targets
    indices, anch = self.find_3_positive(p, targets, anchors)
  File "/home/aistudio/PaddleDetection_YOLOSeries/ppdet/modeling/losses/yolo_loss.py", line 779, in find_3_positive
    gxi = gain[[2, 3]] - gxy  # inverse
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 299, in __impl__
    return math_op(self, other_var, 'axis', axis)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [2] and the shape of Y = [0, 2, 7]. Received [2] in X is not equal to [7] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)
  [operator < elementwise_sub > error]

### 复现环境 Environment

paddle-bfloat          0.1.7
paddledet              2.4.0
paddlefsl              1.0.0
paddlehub              2.0.4
paddlenlp              2.1.1
paddlepaddle-gpu       2.3.1.post101
tb-paddle              0.3.6

pythonn 3.7.4

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by fanyuanxiang** [comment]
!python tools/train.py -c configs/yolov7/yolov7p6_w6_300e_coco.yml --eval

**Comment by nemonameless** [comment]
是训练了多少epoch后出现的呢？
另外单卡不建议训这么大的模型，bs过小效果不会太好。

**Comment by wawatt** [comment]
我也遇到了。是跑起来后，第一个epoch没跑完出现了

**Comment by nemonameless** [comment]
> 我也遇到了。是跑起来后，第一个epoch没跑完出现了

几卡训的，总bs有多大呢？

**Comment by nemonameless** [comment]
谢谢关注。今晚会修下，可以明天来看看，修好了会通知大家~

**Comment by seyosum** [comment]
我也是这种情况，训练一两个Epoch就报这个错，我用的yolov7-l

**Comment by nemonameless** [comment]
先简单规避这个极端情况 修复了。
也请大家也都说下几卡训的总共bs是多少，以及paddle版本以便排查。bs过小会有概率发生这种情况。我是paddle2.3.1训的8卡总bs=256没遇到过。

**Comment by JackYang825** [comment]
+1.  试了下 一样的 bug

**Comment by nemonameless** [comment]
修复了。
再次建议大家说下自己的总bs设置，bs过小训会引起这个bug，不建议单卡训，不建议总bs小于32训，这样精度不会很高训了意义也不大。
如果有资源，建议开大bs到总bs=32以上最好，并且开启amp混合精度训练降低显存，如果没有资源，可以训tiny版模型并始终保持总bs32以上最好。
原版是8卡总bs 8x32=256训的。训自己的数据集强烈推荐使用coco权重做预训练去fintune，参考[fintune训练](https://github.com/nemonameless/PaddleDetection_YOLOSeries#fintune%E8%AE%AD%E7%BB%83)。

**Comment by NwTbbetter** [comment]
报告，v7_tiny也有同样的报错，单卡，paddle2.2.2，batch配置文件没改

**Comment by nemonameless** [comment]
> 报告，v7_tiny也有同样的报错，单卡，paddle2.2.2，batch配置文件没改

请使用paddle2.3.0及以上版本
