### ISSUE TITLE
ppyoloe 评估出现错误 ValueError: (InvalidArgument) multiclass_nms3(): argument (position 4) must be double, but got str (at /paddle/paddle/fluid/pybind/op_function_common.cc:211)

### ISSUE THREAD

**Issue by BainOuO** [PaddlePaddle/PaddleYOLO#64]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

aistudio@jupyter-894455-5140321:~/PaddleYOLO$ python ./tools/eval.py -c ./configs/ppyoloe/ppyoloe_crn_s_400e_coco_tea.yml
W1129 16:28:18.003080  4451 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W1129 16:28:18.007580  4451 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
[11/29 16:28:19] ppdet.data.source.coco WARNING: Found an invalid bbox in annotations: im_id: 112, area: 0.0 x1: 320.00064000000003, y1: 272.00016, x2: 320.00064000000003, y2: 273.00024.
[11/29 16:28:20] ppdet.utils.checkpoint INFO: Finish loading model weights: output/ppyoloe_crn_s_400e_coco_tea/model_final.pdparams
[11/29 16:28:20] ppdet.engine INFO: Eval loader length is 68, eval batch_size is 2.
[11/29 16:28:20] ppdet.engine INFO: Starting evaluation ......

Traceback (most recent call last):
  File "./tools/eval.py", line 193, in <module>
    main()
  File "./tools/eval.py", line 189, in main
    run(FLAGS, cfg)
  File "./tools/eval.py", line 154, in run
    trainer.evaluate()
  File "/home/aistudio/PaddleYOLO/ppdet/engine/trainer.py", line 529, in evaluate
    self._eval_with_loader(self.loader)
  File "/home/aistudio/PaddleYOLO/ppdet/engine/trainer.py", line 503, in _eval_with_loader
    outs = self.model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/architectures/meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/architectures/yolo.py", line 102, in get_pred
    return self._forward()
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/architectures/yolo.py", line 94, in _forward
    yolo_head_outs, self.inputs['scale_factor'])
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/heads/ppyoloe_head.py", line 391, in post_process
    bbox_pred, bbox_num, _ = self.nms(pred_bboxes, pred_scores)
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/layers.py", line 214, in __call__
    return ops.multiclass_nms(bboxes, score, **kwargs)
  File "/home/aistudio/PaddleYOLO/ppdet/modeling/ops.py", line 229, in multiclass_nms
    rois_num, *attrs)
ValueError: (InvalidArgument) multiclass_nms3(): argument (position 4) must be double, but got str (at /paddle/paddle/fluid/pybind/op_function_common.cc:211)

**Comment by logchen** [comment]
一样 ，用yolov5的时候遇到的
File "/root/PaddleYOLO/ppdet/modeling/ops.py", line 228, in multiclass_nms
    output, index, nms_rois_num = _C_ops.multiclass_nms3(bboxes, scores,
ValueError: (InvalidArgument) multiclass_nms3(): argument (position 4) must be double, but got str (at /paddle/paddle/fluid/pybind/op_function_common.cc:211)

**Comment by nemonameless** [comment]
已修复，请拉取最新更新再试试。
以及报bug请按模板说明版本环境信息谢谢。

**Comment by logchen** [comment]
> 已修复，请拉取最新更新再试试。 以及报bug请按模板说明版本环境信息谢谢。

好的，我这边的环境是python3.9， PaddleYOLO [release/2.5]

更新后已修复，谢谢
