### ISSUE TITLE
PaddleYOLO yolov5 训练出错

### ISSUE THREAD

**Issue by lwh104** [PaddlePaddle/PaddleYOLO#67]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

环境：ubuntu 22.04
paddle版本：2.4.0

W1130 14:21:26.796521 3913171 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 11.8, Runtime API Version: 11.7
W1130 14:21:26.804353 3913171 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
Params:  Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=True,
       [46.13829422])
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[11-30 14:21:31 MainThread @logger.py:242] Argv: tools/train.py -c configs/yolov5/yolov5_l_300e_coco.yml --eval --amp
[11-30 14:21:31 MainThread @utils.py:73] paddlepaddle version: 2.4.0.
WARNING:root:cannot import name 'layers' from 'parl' (/home/ubuntu/miniconda3/envs/lwh-paddle/lib/python3.8/site-packages/parl/__init__.py)
<class 'ppdet.modeling.architectures.yolov5.YOLOv5'>
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/data/lwh/PaddleYOLO/ppdet/engine/trainer.py", line 361, in train
    self._flops(flops_loader)
  File "/data/lwh/PaddleYOLO/ppdet/engine/trainer.py", line 1018, in _flops
    flops = flops(self.model, input_spec) / (1000**3)
  File "/home/ubuntu/miniconda3/envs/lwh-paddle/lib/python3.8/site-packages/paddleslim/analysis/flops.py", line 133, in dygraph_flops
    program = dygraph2program(model, inputs)
  File "/home/ubuntu/miniconda3/envs/lwh-paddle/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/ubuntu/miniconda3/envs/lwh-paddle/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lwh-paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lwh-paddle/lib/python3.8/site-packages/paddleslim/core/dygraph.py", line 145, in dygraph2program
    return _dy2prog(layer, inputs, feed_prefix, fetch_prefix, tmp_prefix,
  File "/home/ubuntu/miniconda3/envs/lwh-paddle/lib/python3.8/site-packages/paddleslim/core/dygraph.py", line 202, in _dy2prog
    outputs = layer(*inputs)
  File "/home/ubuntu/miniconda3/envs/lwh-paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 950, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lwh-paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 935, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/data/lwh/PaddleYOLO/ppdet/modeling/architectures/meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "/data/lwh/PaddleYOLO/ppdet/modeling/architectures/yolov5.py", line 95, in get_pred
    return self._forward()
  File "/data/lwh/PaddleYOLO/ppdet/modeling/architectures/yolov5.py", line 80, in _forward
    yolo_head_outs = self.yolo_head(neck_feats)
  File "/home/ubuntu/miniconda3/envs/lwh-paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 950, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/ubuntu/miniconda3/envs/lwh-paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 935, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/data/lwh/PaddleYOLO/ppdet/modeling/heads/yolov5_head.py", line 124, in forward
    assert len(feats) == len(self.anchors)
TypeError: object of type 'Variable' has no len()

**Comment by nemonameless** [comment]
你好，我测试过装paddlepaddle2.4.0训也是可以的。请再检查下环境问题，比如打印GPU数和版本号看看。

**Comment by lwh104** [comment]
> 你好，我测试过装paddlepaddle2.4.0训也是可以的。请再检查下环境问题，比如打印GPU数和版本号看看。

好的，我再检查一下。

GPU数量只有1个 4090
Linux装的CUDA版本是11.8，Paddle装的CUDA11.7，不知道有没有影响，但是测试过可以调用GPU。

**Comment by nemonameless** [comment]
训其他模型也有这个问题吗？有几个python环境，装过paddle版本呢？

**Comment by lwh104** [comment]
> 训其他模型也有这个问题吗？有几个python环境，装过paddle版本呢？

试过yolov7，没有这个问题。
有9个python环境，但只有我用的这个环境是装的paddle的，2.4版本的

**Comment by nemonameless** [comment]
将这句注释掉再试试试试`assert len(feats) == len(self.anchors)`

**Comment by lwh104** [comment]
> 

好的，等我明天试试
