### ISSUE TITLE
Out of memory error on GPU 0. 

### ISSUE THREAD

**Issue by cunjing56** [PaddlePaddle/PaddleYOLO#68]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug描述 Describe the Bug

python tools/train.py -c configs/yolov7/yolov7_l_300e_rice.yml --eval

D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\vision\transforms\functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
W1203 23:05:08.491394  7588 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.8, Runtime API Version: 11.2
W1203 23:05:08.496448  7588 device_context.cc:465] device: 0, cuDNN Version: 8.1.
W1203 23:05:09.667534  7588 device_context.h:397] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\tensor\creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Traceback (most recent call last):
  File "tools/train.py", line 172, in <module>
    main()
  File "tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "D:\pkg\PaddleYOLO\ppdet\engine\trainer.py", line 411, in train
    outputs = model(data)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\pkg\PaddleYOLO\ppdet\modeling\architectures\meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "D:\pkg\PaddleYOLO\ppdet\modeling\architectures\yolov5.py", line 92, in get_loss
    return self._forward()
  File "D:\pkg\PaddleYOLO\ppdet\modeling\architectures\yolov5.py", line 73, in _forward
    body_feats = self.backbone(self.inputs)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\pkg\PaddleYOLO\ppdet\modeling\backbones\yolov7_elannet.py", line 594, in forward
    x = layer(x)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\container.py", line 98, in forward
    input = layer(input)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\pkg\PaddleYOLO\ppdet\modeling\backbones\yolov7_elannet.py", line 79, in forward
    x_2 = self.bottlenecks[i](x_2)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\pkg\PaddleYOLO\ppdet\modeling\backbones\csp_darknet.py", line 85, in forward
    x = self.bn(self.conv(x))
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\nn\layer\conv.py", line 677, in forward
    use_cudnn=self._use_cudnn)
  File "D:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\nn\functional\conv.py", line 123, in _conv_nd
    pre_bias = getattr(_C_ops, op_type)(x, weight, *attrs)
SystemError: (Fatal) Operator conv2d raises an struct paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 21.001465MB memory on GPU 0, 9.999512GB memory has been allocated and available memory is only 0.000000B.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

 (at ..\paddle\fluid\memory\allocation\cuda_allocator.cc:79)
. (at ..\paddle\fluid\imperative\tracer.cc:221)

### 复现环境 Environment

win11
cuda 11.2
paddle2.2.2

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
你好，报错请提供更多代码改动的信息等。Out of memory 是最基础的报错，可以训练命令后加上`--amp`开启混合精度训练，也可以降低batch_size或减小输入尺度，另外尽量不要单卡训练，不要让总bs过小去训，这些文档上都写明了。
运行请确保仔细阅读了文档所写后再尝试  https://github.com/PaddlePaddle/PaddleYOLO#%E6%95%99%E7%A8%8B 

yolov7必须使用paddle2.3以上版本，win下使用develop 也就是0.0.0版本(版本是高于2.3.0的)，综合来看你只要安装develop 也就是0.0.0版本   https://www.paddlepaddle.org.cn/install/quick/zh/2.0rc-linux-source?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html

最后再多说一句，没有很大资源的时候不要去训这种大模型，或者干脆换yolov7_tiny或ppyoloe+ s m l 去训，注意要加载coco权重做预训练。
