### ISSUE TITLE
YOLOV7训练报错

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleYOLO#9]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

Traceback (most recent call last):
  File "/home/zhaohaibin/paddle/PaddleDetection_YOLOSeries-develop/tools/train.py", line 172, in <module>
    main()
  File "/home/zhaohaibin/paddle/PaddleDetection_YOLOSeries-develop/tools/train.py", line 168, in main
    run(FLAGS, cfg)
  File "/home/zhaohaibin/paddle/PaddleDetection_YOLOSeries-develop/tools/train.py", line 132, in run
    trainer.train(FLAGS.eval)
  File "/home/zhaohaibin/paddle/PaddleDetection_YOLOSeries-develop/ppdet/engine/trainer.py", line 509, in train
    outputs = model(data)
  File "/home/zhaohaibin/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/zhaohaibin/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zhaohaibin/paddle/PaddleDetection_YOLOSeries-develop/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/home/zhaohaibin/paddle/PaddleDetection_YOLOSeries-develop/ppdet/modeling/architectures/yolov5.py", line 98, in get_loss
    return self._forward()
  File "/home/zhaohaibin/paddle/PaddleDetection_YOLOSeries-develop/ppdet/modeling/architectures/yolov5.py", line 88, in _forward
    yolo_losses = self.yolo_head(neck_feats, self.inputs)
  File "/home/zhaohaibin/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/zhaohaibin/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zhaohaibin/paddle/PaddleDetection_YOLOSeries-develop/ppdet/modeling/heads/yolo_head.py", line 727, in forward
    self.anchors)
  File "/home/zhaohaibin/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/zhaohaibin/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/zhaohaibin/paddle/PaddleDetection_YOLOSeries-develop/ppdet/modeling/losses/yolo_loss.py", line 513, in forward
    inputs, targets, gt_targets['image'], anchors)
  File "/home/zhaohaibin/paddle/PaddleDetection_YOLOSeries-develop/ppdet/modeling/losses/yolo_loss.py", line 593, in build_targets
    indices, anch = self.find_3_positive(p, targets, anchors)
  File "/home/zhaohaibin/paddle/PaddleDetection_YOLOSeries-develop/ppdet/modeling/losses/yolo_loss.py", line 784, in find_3_positive
    gxi = gain[[2, 3]] - gxy  # inverse
  File "/home/zhaohaibin/miniconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 264, in __impl__
    return math_op(self, other_var, 'axis', axis)
RuntimeError: (PreconditionNotMet) The Tensor's element number must be equal or greater than zero. The Tensor's shape is [-1, 2] now
  [Hint: Expected numel() >= 0, but received numel():-2 < 0:0.] (at /paddle/paddle/fluid/framework/tensor.cc:59)
  [operator < elementwise_sub > error]

### 复现环境 Environment

--paddlepaddle:2.2.2
--python: 3.7
--CUDA: 10.2
--cudnn: 8.3

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
paddle版本推荐使用2.3.0版本及以上
